### ISSUE TITLE
util-deprecate error

### ISSUE THREAD

**Issue by ClubPEC** [hashlips-lab/nft-erc721-collection#100]
Dear Daniel/Marco

Hope you guys are well.

Whilst trying to run "Yarn Build" in Minting-dapp
 
Module build failed: Module not found:
"./node_modules/readable-stream/lib/_stream_writable.js" contains a reference to the file "util-deprecate".       
This file can not be found, please check it for typos or update it if the file got moved.

Entrypoint main = main.js
Entrypoint _tmp_copy = 3 auxiliary assets
webpack compiled with 3 errors
error Command failed with exit code 1.

**Comment by liarco** [comment]
Hi @ClubPEC,
would you please add the following information?
1. operating system
2. collection project version
3. steps to reproduce the error

That error is extremely generic, it might even be related to a broken installation of the dependencies or of the required software (nodejs, yarn, etc.).

The DAPP build [is now continuously tested on every change we make](https://github.com/hashlips-lab/nft-erc721-collection/actions/workflows/dapp-build.yaml) and on every operating system (Linux, macOS, and Windows), so we are pretty sure that everything works fine as long as you have everything set up correctly on your machine.

Thank you

**Comment by ClubPEC** [comment]
> 
Dear Marco

operating system :- Windows 11
collection project version :- 2.0.0
steps to reproduce the error :- 
PS D:\EON DATA\OneDrive - \Desktop\ERC721A_2.0\minting-dapp> node -v
v16.14.0
PS D:\EON DATA\OneDrive -\Desktop\ERC721A_2.0\minting-dapp> yarn -v
1.22.15
\Desktop\ERC721A_2.0\minting-dapp> yarn build
yarn run v1.22.15
warning ..\..\package.json: No license field
$ encore production --progress
Running webpack ...

99% done plugins FriendlyErrorsWebpackPlugin ERROR  Failed to compile with 1 errors          13:44:04

Module build failed: Module not found:
"./node_modules/readable-stream/lib/_stream_writable.js" contains a reference to the file "util-deprecate".       
This file can not be found, please check it for typos or update it if the file got moved.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

My Smart contract is successfully complied and Deployed on mainnet. Thanks to you and Daniel that I was Lucky enough to deploy for only ETH 0.1055 ($256).
Yarn Dev-Server only worked once after that it never worked & Yarn build is not working from start.

Again You and Daniel been a kind of Big Contributor to non tech Artist like me.

Hope to get this Minting dapp working and finally reveal my collection to world.

Thanks 
PEC

**Comment by liarco** [comment]
Ok, that error is really strange, but please try the following steps:
1. remove the `/minting-dapp/node_modules`
2. run `yarn` again
3. when all dependencies are installed run `yarn build`

It seems like your dependencies are broken or maybe there is some windows configuration stuff which is making the build fail...

**Comment by ClubPEC** [comment]
Hi Marco
Followed your instructions ...

Still same error of Util-Deprecate 

Please check attached png. On left you can see no Node-Modules and no Build generated.

Question - Can I reload complete [nft-erc721-collection](https://github.com/hashlips-lab/nft-erc721-collection) again ? Even if my smart contract is Deployed and live on ether scan ? 

![Minting-Dapp error](https://user-images.githubusercontent.com/100386069/157481189-4fe57e11-c4b2-4b63-a5ac-cf3d7a3a1c81.png)

Thank you for your time and support 

PEC

**Comment by liarco** [comment]
@ClubPEC this is really strange: from your screenshot it seems like your `/minting-dapp/node_modules` folder is almost empty (it just contain one folder) while it should have all the DAPP dependencies in it. Are you sure you run `yarn` inside the DAPP folder?

**Comment by ClubPEC** [comment]
Dear Marco

Hope you are well

All Sorted, There is nothing wrong with the Minting-Dapp. It was my Windows. Had to get another machine to try on. It is working absolutely fine. In-fact its an amazing help.

I was wondering if there is any collaboration opportunity for My project & Hashlips (Daniel & You)? Let me know how can I DM you ?

Once again thank you ever so much for this amazing nft-erc721-collection.

Thanks 

PEC

**Comment by liarco** [comment]
Happy to hear you solved the issue, I can't wait to have time to publish a video about how to setup all operating systems properly...

Anyway, feel free to contact me (contacts can be found in my GitHub profile page).
