### ISSUE TITLE
DAPP works on my local server does not work on my cpanel?

### ISSUE THREAD

**Issue by JSwizzleCrypto** [hashlips-lab/nft-erc721-collection#103]

**Comment by JSwizzleCrypto** [comment]
My previous case was closed but I’m not sure why, nothing was resolved

**Comment by liarco** [comment]
I'm sorry, but I'm not supposed to solve your specific problems with other services. GitHub issues are meant for reporting issues or misbehavior of my software. I already explained everything in [the previous issue](https://github.com/hashlips-lab/nft-erc721-collection/issues/102#issuecomment-1062995830).

If you find something wrong with the app, then I will be more than happy to solve that, but in this case it seems like you did something wrong with your hosting platform, so I can't help with that.
