### ISSUE TITLE
Minting Dapp working on local, but not on public server

### ISSUE THREAD

**Issue by Babarlafee** [hashlips-lab/nft-erc721-collection#104]
Hello!

I ran into users facing this issue as well. I wonder if the mintiing dapp build works for anyone on their servers?

When running locally, the dapp works perfectly fine.
However, when I upload public file to my server I can only see the mint buttons, which do not function, as well as a corrupted layout.

I had succes uploading previous personal builds so I wonder if the dappbuilder works fine for anyone or if you have a fix?

**Comment by JSwizzleCrypto** [comment]
I am having this same exact issue, and have not been able to find a solution either.

**Comment by alanwatts07** [comment]
It works guys... you gotta do yarn run production, or npx encore production. Then the build folder will show up.

**Comment by liarco** [comment]
@alanwatts07 thank you for taking time to answer this, but the correct command is actually `yarn build`.

The reason for this is that the `yarn dev-server` is not compiling to your `public` folder, it's just serving the files on the fly from a development web server, so you have to run the production build once you are ready to deploy.

@Babarlafee let me know if this solves your issue.
@JSwizzleCrypto is having another kind of issue: he is building the DAPP correctly but the web server is not serving the files correctly, so I must understand what's going on there, but I think it has nothing to do with this project.

**Comment by JSwizzleCrypto** [comment]
@Babarlafee did this work for you? I am still having this issue sadly!

Let me know if this worked for you!

My build works perfectly fine, @liarco just checked my files when I was messing around with them and saw them at a time when they were in the wrong spot! 

I tried to figure out the solution all night and still had no success lmk if you have a solution!

**Comment by Babarlafee** [comment]
@liarco Thank you for taking the time to reply, I found the solution on my end. 

SOLUTION: 

1. if you have a blank page with logo only on it: only import the "build" folder with the html file inside it. Empty all caches and try in a incognito window.
2.Reinstalled the dapp, I probably messed something up during installation.

**Comment by JSwizzleCrypto** [comment]
@Babarlafee with the html file inside it?

@liarco said that is not what you are suppose to do?

**Comment by JSwizzleCrypto** [comment]
@Babarlafee I also tried this exact fix last night and it did not work for me? 

Any other solutions you have found?

**Comment by liarco** [comment]
@JSwizzleCrypto your DAPP is working perfectly fine, it was your fault. I also sent you a screenshot on your issue (#102). I really think you should take your time in order to learn the basics of how web2 works (at least).

Don't get me wrong, but you probably shouldn't run an NFT project on your own if you are lacking the minimum required knowledge. How would you be able to support your community needs in the future? You should at least hire some devs to help you with the stuff you don't know... anyway that's not my business, just my personal opinion.

Thank you @Babarlafee for your feedback and sorry for the noise...
