### ISSUE TITLE
Contract Verification Error

### ISSUE THREAD

**Issue by Robcar-10** [hashlips-lab/nft-erc721-collection#116]
Hello, I am having issues when I run the command to verify the deployed contract. I am running this command: yarn verify (ContactAddress) --network truffle. I deployed the contract successfully but verifying it I get this error: 

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

How could I resolve this issue?

**Comment by Patrizi5** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/97971328/157977208-fa68c295-69fe-4d0c-b6b8-d23eb857f210.png)
 dont know what to do with this

**Comment by BlueGreninja** [comment]
> 

Hi @Robcar-10 Check pinned post, Rinkeby network might be facing some issues due to high traffic. Patience is all that's needed
