### ISSUE TITLE
Truffle Dashboard Blank White Page

### ISSUE THREAD

**Issue by granthughes1999** [hashlips-lab/nft-erc721-collection#119]
Hello,

I duplicated my deploy folder to keep a backup copy of my project, I then went ahead and followed the same steps I did on the original fully functional folder. This includes running sudo -s and npm install truffle -g in the new duplicate terminal. yes, I know this is not how it is suggested to be done, this is however how I did it the first time and its the only way I could get it truffle to install.

Now the issue is no matter what folder I run truffle dashboard in, I get a blank white truffle dashboard at http://localhost:24012/. There is no longer a connect Wallet option. I deleted the duplicate folder and started a new nft-erc721-collection-main zip folder, the same exact issue appears here too.

Thanks,

**Comment by liarco** [comment]
Hi @granthughes1999, Truffle Dashboard is a stand-alone tool so it's not related to our project in any way (you can also run it from any folder and it's gonna work exactly the same.

I suggest you reporting this issue to the Truffle team on GitHub. Unfortunately I'm on mobile now so I can't send you the link, but you can find it pretty easily.

Thank you, I hope you will be able to solve this soon. I'm also gonna publish 3 videos early next week about how to setup any operating system with all the basic requirements. You will find these on my YouTube channel (Liarco DevTips).

**Comment by granthughes1999** [comment]
Thanks @liarco,

This lead me to the truffle GitHub, where I noticed they just released truffle v5.5.4.
My solution was to simply do the following

> npm uninstall -g truffle
> npm install -g truffle@v.5.5.3

**Comment by liarco** [comment]
Oh, that's good to know. Thank you very much!
