### ISSUE TITLE
Royalties percentage and specified wallet

### ISSUE THREAD

**Issue by gitrevo** [hashlips-lab/nft-erc721-collection#12]
Hi again,

How can we add royalties % for secondary markets and royalties wallet address directly into this smart contract? If yes, mind to point which links/video shows this line of codes?

It would be great to assign this royalties in the contract so it will work in all secondary markets should we forget to set it up (os, looksrare, x2y2 etc.).

Thanks again for the great tutorials!

**Comment by liarco** [comment]
Hi @gitrevo,
thank you for your feedback. There is still no standard way to do that. OpenSea is supporting [a custom way to handle it](https://docs.opensea.io/docs/contract-level-metadata) so you may try implementing it if you wish. There shouldn't be any compatibility issue. _(I just suggest going for a dynamic variable as any other URI so you won't get stuck with an initial value if you need to update it)_

I have to point out that it's unlikely that we will introduce non-standard features like this in the default contract unless it becomes really widely adopted.

**Comment by gitrevo** [comment]
contract GitRevoNFT is ERC721 {
    function contractURI() public view returns (string memory) {
        return "https://gitrevo.io/contract-metadata.json";
    }
}

In contract-metadata.json

{
  "name": "GitRevoNFT",
  "description": "This is Git Revo NFT",
  "image": "https://gitrevo.io/gitrevo.png",
  "external_link": "https://gitrevo.io",
  "seller_fee_basis_points": 500, # Indicates a 5% seller fee.
  "fee_recipient": "0xA97F337c39cccE66adfeCB2BF99C1DdC54C2D721" # Where seller fees will be paid to.
}

Will this actually works on OpenSea only? Or it will work on other marketplace (looksrare, x2y2 etc.) as well?

**Comment by liarco** [comment]
@gitrevo as I said:

> There is still no standard way to do that. OpenSea is supporting [a custom way to handle it](https://docs.opensea.io/docs/contract-level-metadata)

So that is a non-standard implementation suggested by OpenSea only. Other marketplaces might be using it as well, but to my knowledge there is no warranty that all the marketplaces are going to use it. I'm sorry.

**Comment by granthughes1999** [comment]
> contract GitRevoNFT is ERC721 { function contractURI() public view returns (string memory) { return "https://gitrevo.io/contract-metadata.json"; } }
> 
Hey @liarco or @gitrevo, 

Could you explain where that https://gitrevo.io/contract-metadata.json is supposed to point to exactly?


> In contract-metadata.json
> 
> { "name": "GitRevoNFT", "description": "This is Git Revo NFT", "image": "https://gitrevo.io/gitrevo.png", "external_link": "https://gitrevo.io", "seller_fee_basis_points": 500, # Indicates a 5% seller fee. "fee_recipient": "0xA97F337c39cccE66adfeCB2BF99C1DdC54C2D721" # Where seller fees will be paid to. }
> 
> Will this actually works on OpenSea only? Or it will work on other marketplace (looksrare, x2y2 etc.) as well?

Could you also explain what to do with this .json file? Do I add contract-metadata.json as a file to the nft-erc721-collection-main ?
