### ISSUE TITLE
npm i -g truffle ,getting an error!!!! 

### ISSUE THREAD

**Issue by Puppilshaw** [hashlips-lab/nft-erc721-collection#123]
![Skärmavbild 2022-03-13 kl  15 28 06](https://user-images.githubusercontent.com/101512981/158064560-b34e734c-eb12-41fb-bc3a-a3ddc6cef557.png)
![Skärmavbild 2022-03-13 kl  15 28 38](https://user-images.githubusercontent.com/101512981/158064576-d2dbd1e7-cc6a-4240-ba32-066ecb9479ea.png)

what do I need to fix to not have this error I'm a noob so simple explaining please !!!!

**Comment by Zekel97** [comment]
Hello! It looks like you're on MacOS, so I suggest you to [watch and follow this video](https://www.youtube.com/watch?v=acqXzKN5Xys) because probably you misconfigured or misused something!
