### ISSUE TITLE
Changing MaxMint Limit for Wallet rather than Txn

### ISSUE THREAD

**Issue by georgekaraan** [hashlips-lab/nft-erc721-collection#125]
Is there a way to change the limit of how many NFTs a wallet can mint? The contract only specifies a max mint amount per txn. 

In my case I had it set to 2, but I minted 1 and then tried to mint another 1 and it didn't let me.

**Comment by liarco** [comment]
Hi @georgekaraan this topic has been discussed many times, you can find a lot of info in #42. In that issue I explain the reason why I don't want to implement something like that in this project. I hope it helps.

Thank you for your understanding. 🙏

**Comment by georgekaraan** [comment]
@liarco thank you so much !!! Appreciate your reply and your amazing work.
