### ISSUE TITLE
Minting DAPP

### ISSUE THREAD

**Issue by locache** [hashlips-lab/nft-erc721-collection#127]
Hello and thank you both for all of the work you do!!!

Everything seems to work fine up until I run the local dev server command (yarn dev-server) for the DAPP. I get the attached error about the contract name. The first time I got this error the contract was named 'SavagePatch' with single quotes. Then I redeployed a new contract with the name you see in the screen shot with "" thinking that would solve the error.   Thank you

![image](https://user-images.githubusercontent.com/32690966/158289125-16089317-de55-434a-9445-437374417c50.png)

**Comment by CaptainJoyboy** [comment]
I think I also found that issue, but I disabled typescript check on the Dapp.tsx file just to be able to build.

Add this comment at the top of the file `/* tslint:disable */`

**Comment by locache** [comment]
Thanks, I tried that, saved the file, and I still get the same error.

![image](https://user-images.githubusercontent.com/32690966/158387418-bf68f324-b33c-4ad6-adf4-97304132b461.png)

**Comment by Zekel97** [comment]
Hello! It looks like you misconfigured something and you seem to be on Windows, so I suggest you to [follow this video](https://www.youtube.com/watch?v=zjlg-0622PU) as it explains everything!

**Comment by locache** [comment]
Thanks, I had to follow the video and then start over with the DAPP\SC. Now it works!
