### ISSUE TITLE
Wallet of owner tests fail

### ISSUE THREAD

**Issue by tomvanleeuwennl** [hashlips-lab/nft-erc721-collection#128]
Hi,

After running: 
> npx hardhat test

right after cloning this repository the "Wallet of owner tests" fail.

This is the error message I get:
`AssertionError: expected [ BigNumber{ _hex: '0x01', …(1) } ] to deeply equal [ BigNumber { value: "1" } ] + expected - actual at Context.<anonymous> (test/index.ts:205:73)`

What is going wrong here?

**Comment by liarco** [comment]
Hi @tomvanleeuwennl the whole repo is tested automatically at each push so all tests should pass correctly, but I see you are using `npx` in order to call `hardhat` directly, you should use `yarn test` (it might not be the issue, but maybe you are testing using a different hardhat version compared to the one used by our project).

Let me know if using the correct tools change the result. Thank you.

**Comment by tomvanleeuwennl** [comment]
Here you can see the results with yarn test. Same issue...

<img width="1014" alt="Schermafbeelding 2022-03-17 om 18 18 54" src="https://user-images.githubusercontent.com/58329367/158857943-2763e48a-b0d2-40f6-b74a-85a2cc71ec47.png">

As for what I can see, the test script is checken 0x01 with 1. And this is not matching.

**Comment by VeriumNFT** [comment]
Hello, I reproduced a similar error when trying to set the whitelist price to 0.00 or 0

After setting to anything higher than 0 my test passed all 8 checks. I tried changing line 44
Previous: `require(_mintAmount > 0 && _mintAmount <= maxMintAmountPerTx, 'Invalid mint amount!');`<br>
New: `require(_mintAmount >= 0 && _mintAmount <= maxMintAmountPerTx, 'Invalid mint amount!');`

Same results after changing line 44. I currently have it set to 0.000001 ($0.003) which is the closest I can get to "Free". 

![Screenshot (24)_LI](https://user-images.githubusercontent.com/95852477/159100305-30e829d3-2b09-4d74-8cc4-a706a9d56f18.jpg)

**Comment by tomvanleeuwennl** [comment]
I think I've found the problem!

Because at line 80 address latestOwnerAddress; is set to nothing.

Going through the while loop at 82 at line 86 the latestOwnerAddress can be set to the owner address. When set once, line 89 will always be true in every iteration of the coming while repeats right? Even when a token is burned.

So at line one in the while loop there must be a latestOwnerAddress = address(0); or remove line 80 and place address latestOwnerAddress; as line one in the while loop. 

Or am I missing something here?

**Comment by liarco** [comment]
Thank you @tomvanleeuwennl, I can't check this right now but I reopened this because, from what you say, this might require further investigation. I'm only worried because I still can't reproduce your issue... You said this happens just by checking out the repo and running tests, but this should happen both on CI and locally...

**Comment by tomvanleeuwennl** [comment]
I’ll reproduce it tomorrow and make a test change proposal.

And the other issue I’ve found needs indeed further investigation. I will also check this tomorrow.

**Comment by tomvanleeuwennl** [comment]
It was late I guess yesterday ;-) The comments about line 80 with latestOwnerAddress is misinterpreted by me and is working in the right way.

After running a new yarn update also the walletofowner seems to work fine now. Really don't know how it first come up with those errors.

But all is solved miraculously. You can close this ticket.

**Comment by liarco** [comment]
> The comments about line 80 with latestOwnerAddress is misinterpreted by me or is it not?

@tomvanleeuwennl I think that leaving the variable unset should not be a problem there, but I think might have spot a possible issue with the `burn` feature (which is not officially supported by the contract, but I would like to double-check this).

**Comment by tomvanleeuwennl** [comment]
@liarco Yes, it might! I think there is a problem there too.

But adding a line directly at the first line in the while loop like "latestOwnerAddress = address(0);" or removing line 80 and adding "address = latestOwnerAddress;" at the first line in the while loop will result in running out of gas.

**Comment by tomvanleeuwennl** [comment]
I am further investigating because I now experience something going wrong with a some what more difficult smart contract with burning tokens.

Can you please elaborate what you mean with:

/**
     * It gradually moves to O(1) as tokens get transferred around in the collection over time.
     * */
At the ownershipOf function. I cannot get my head around the O(1) explanation.

Because I think here is something done which also needs to be done at the walletofowner function.

**Comment by liarco** [comment]
Hi @tomvanleeuwennl, that function is from a third-party library (the `ERC721A` contract from the Azuki team), but the comment is referring to the [computational complexity](https://en.wikipedia.org/wiki/Computational_complexity) of the algorithm. (long story short: that function might use a huge amount of gas so it should never be used "on-chain")

This project was not originally meant to support the `burn` function (it wasn't even supported by the Azuki contract if I'm not mistaken), but now that it can be implemented it should be supported by `walletOfOwner` too.

I need to do some specific tests about this.

**Comment by tomvanleeuwennl** [comment]
@liarco I've proposed a pull request in the walletofowner function. Can you check if this is right? It results in the right outcomes for my situation.

**Comment by joven1555** [comment]
My test is getting the following errors below using the latest repo.  Is this expected?


PS C:\Users\joven\Documents\smart_contract_eth_04-15-2022_v2\smart-contract> yarn test
yarn run v1.22.15
warning ..\..\..\package.json: No license field
$ hardhat test
No need to generate any newer typings.


  HFHEthereum
    ✔ Contract deployment (189ms)
    ✔ Check initial data (147ms)
    ✔ Before any sale (239ms)
    1) Whitelist sale
    2) Pre-sale (same as public sale)
    ✔ Owner only functions (177ms)
    3) Wallet of owner
    - Supply checks (long)
    ✔ Token URI generation (107ms)


  5 passing (2s)
  1 pending
  3 failing

  1) HFHEthereum
       Whitelist sale:

      AssertionError: Expected transaction to be reverted
      + expected - actual

      -Transaction NOT reverted.
      +Transaction reverted.



  2) HFHEthereum
       Pre-sale (same as public sale):
     AssertionError: expected promise to be rejected with 'Error' but it was fulfilled with { …(22) }


  3) HFHEthereum
       Wallet of owner:

      AssertionError: expected [ BigNumber { value: "2" }, …(3) ] to deeply equal [ BigNumber { value: "2" }, …(2) ]
      + expected - actual

           "_hex": "0x03"
           "_isBigNumber": true
         }
         {
      -    "_hex": "0x04"
      +    "_hex": "0x06"
           "_isBigNumber": true
         }
      -  {
      -    "_hex": "0x07"
      -    "_isBigNumber": true
      -  }
       ]

      at Context.<anonymous> (test\index.ts:208:83)



error Command failed with exit code 3.
