### ISSUE TITLE
Whitelist function doesn't work

### ISSUE THREAD

**Issue by 5MetaLab** [hashlips-lab/nft-erc721-collection#129]
i've succesfully deployed my contract and verified it on Mumbai Testnet Thank you guys for you amazing work. All the contract functions work fine also on Polygon chain. 
The only problem is whitelisting: after updating the whitelist.json file on VSC and launch the command "yarn whitelist-open --network testnet" the terminal complete the operation and create a new hash root.

<img width="688" alt="terminal_whitelisting" src="https://user-images.githubusercontent.com/101571132/158406014-53672390-444f-4ab8-86e7-c82fa536815d.png">

 If i read the contract on polygon scan the merkle root is update, but if i put the whitelisted address on proof return: false.
<img width="715" alt="Schermata 2022-03-15 alle 15 48 34" src="https://user-images.githubusercontent.com/101571132/158406100-ce95e885-b011-4816-82e8-56271d412e4d.png">
<img width="715" alt="Schermata 2022-03-15 alle 15 48 12" src="https://user-images.githubusercontent.com/101571132/158406188-e0c8e745-62ef-461b-a3f7-e85ce055e8b0.png">

In addition i'm able to mint with every address even only the whitelist sale is open. 

<img width="462" alt="Schermata 2022-03-15 alle 15 59 04" src="https://user-images.githubusercontent.com/101571132/158407047-e0275474-a71d-4399-a0af-2a5e7e571463.png">

Anyone same issues? Thank you in advance!!!

**Comment by liarco** [comment]
Hi @5MetaLab first of all I must say that support for Polygon is not officially ready yet (this should not be related to what is happening here, but I must warn you if you plan to use this in production). Also, you should not use a whitelist with just one address in it, that is an edge-case that might break the Merkle Tree library.

That said, please make sure that the contract is "paused" when opening a whitelist sale, having both a whitelist and public sale open might create confusion in the DAPP logic.

During a whitelist sale you should have the following values:
- whitelistMintEnabled: `true`
- paused: `true`

During a pre-sale/public sale you should have the following values:
- whitelistMintEnabled: `false`
- paused: `false`

Let me know if this helps.

**Comment by 5MetaLab** [comment]
thank you! i think this is the problem! how many adresses should be in the list at least? more than one is enough?
