### ISSUE TITLE
Yarn dev-server ERROR: 

### ISSUE THREAD

**Issue by miltonisblurrd** [hashlips-lab/nft-erc721-collection#133]
Hello, as I am getting ready to deploy on the local dev network I keep getting this error after I type ' yarn dev-server'
![Screen Shot 2022-03-15 at 5 03 08 PM](https://user-images.githubusercontent.com/42359159/158491842-1b6e4124-6862-4eb8-a728-c4d7a21942ef.png)

Not sure exactly what is causing this error and how to fix it. Any assistance would be great, thank you so much in advance.

**Comment by aabertente** [comment]
I recommend you to watch this video : https://www.youtube.com/watch?v=zjlg-0622PU

**Comment by Zekel97** [comment]
Hi! Maybe you didn't properly configured some tools or didn't follow every step as shown [in this video](https://www.youtube.com/watch?v=acqXzKN5Xys). Try starting again with a fresh project!
