### ISSUE TITLE
Error: listen EADDRINUSE: address already in use 127.0.0.1:8080

### ISSUE THREAD

**Issue by Puppilshaw** [hashlips-lab/nft-erc721-collection#134]
![Skärmavbild 2022-03-16 kl  01 34 27](https://user-images.githubusercontent.com/101512981/158494181-f4820c8f-dbb6-47b3-a731-2150e764d36d.png

can anybody help me fix this?

**Comment by miltonisblurrd** [comment]
I am getting this same exact error my sel
![Screen Shot 2022-03-15 at 5 03 08 PM](https://user-images.githubusercontent.com/42359159/158496525-71632392-f77d-4cc3-b5c7-9cef36b7068c.png)
f

**Comment by aabertente** [comment]
I recommend you to watch this video : https://www.youtube.com/watch?v=zjlg-0622PU

**Comment by Zekel97** [comment]
Hi! It seems you're using MacOs, so I suggest you to [follow this video](https://www.youtube.com/watch?v=acqXzKN5Xys) and start fresh with a new project, as everything you need to know is explained there.
