### ISSUE TITLE
execution reverted : invalid proof

### ISSUE THREAD

**Issue by meltapollo** [hashlips-lab/nft-erc721-collection#140]
hello!! Im having an error because i added a new wallet to whitelist.json, generated a new root hash then updated it on the contract, Now whenever whitelisted members go to mint it says "execution reverted : invalid proof" please help! How can i fix this?

**Comment by VeriumNFT** [comment]
https://github.com/hashlips-lab/nft-erc721-collection/issues/15#issuecomment-1046621204

**Comment by liarco** [comment]
> [#15 (comment)](https://github.com/hashlips-lab/nft-erc721-collection/issues/15#issuecomment-1046621204)

The issue above might help, also please remember that you should have at least 2 addresses for the Merkle Tree to work properly.
