### ISSUE TITLE
error Couldn't find the binary git

### ISSUE THREAD

**Issue by arturbiotonico** [hashlips-lab/nft-erc721-collection#145]
Hello Hashlips!!

thanks for your excelent job!
Can u help me with this yarn inssue

yarn install v1.22.15
warning package.json: No license field
warning @hashlips-lab/nft-erc721-collection-smart-contract@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git

**Comment by Jam6w** [comment]
Hey Hashlips ..

I Have The Same Problem too.

Can You Please Help Us With This Problem

Thanks..

**Comment by Jam6w** [comment]
Hey bro..

I found the solution for this problem

You should install "git" from this site :

https://git-scm.com/

**Comment by GerhardDBA** [comment]
> Hello Hashlips!!
> 
> thanks for your excelent job! Can u help me with this yarn inssue
> 
> yarn install v1.22.15 warning package.json: No license field warning @hashlips-lab/nft-erc721-collection-smart-contract@1.0.0: No license field [1/4] Resolving packages... [2/4] Fetching packages... error Couldn't find the binary git

Yes, same for me also

**Comment by GerhardDBA** [comment]
> Hey bro..
> 
> I found the solution for this problem
> 
> You should install "git" from this site :
> 
> https://git-scm.com/

many thanks, this did the trick! Had to install and restart VS Code, when re-running yarn, it now completed successfully

**Comment by liarco** [comment]
Hi @Jam6w, thank you for taking time to share your solution!

For anyone struggling with this, please take a look at [the video section on the README file](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials), there you will find step-by-step tutorials from OS setup to project usage.
