### ISSUE TITLE
When is the next stable update releasing?

### ISSUE THREAD

**Issue by explorion** [hashlips-lab/nft-erc721-collection#146]
Hey Marco,
Hope you are all dope!

I noticed you recently added polygon to the main branch
When is the next stable update coming up? Also, are you planning on making more videos on how to use depository after the updates?

The videos will be of great help to the community

Take care

**Comment by liarco** [comment]
Hi @explorion, stuff is coming... new videos will be published (some have already been published) as well as new features. 😉
