### ISSUE TITLE
Execution reverted: Invalid proof

### ISSUE THREAD

**Issue by frank-martinez-27** [hashlips-lab/nft-erc721-collection#15]
Hi,

I followed the Youtube tutorial but Im getting the "Execution reverted: Invalid proof!" Error message when I click the Mint button on Rinkeby network. I have tried with 2 different public rinkeby wallets I own with fake ETH in both but no luck. Any recommendation?

**Comment by liarco** [comment]
Hi @frank-martinez-27, it seems like you are trying to mint during a whitelist sale, but your addresses are not in the whitelist. Can you please confirm this?

Remember that you must run the `yarn whitelist-open` command again whenever you change the `whitelist.json` files (as well as updating the DAPP if you are not using `yarn dev-server`).

**Comment by frank-martinez-27** [comment]
@liarco I didnt see this issue anymore so Ill close this. Thank you!
