### ISSUE TITLE
Error when trying to rename contract

### ISSUE THREAD

**Issue by Celpu** [hashlips-lab/nft-erc721-collection#152]
Hi i cannot rename my contract, i dont know why:

PS C:\Users\jerome\Desktop\nft-erc721-collection-2.0.0\smart-contract> yarn rename-contract jeromescontract      
yarn run v1.22.15
$ hardhat rename-contract jeromescontract
An unexpected error occurred:

config/CollectionConfig.ts:2:50 - error TS2306: File 'C:/Users/jerome/Desktop/nft-erc721-collection-2.0.0/smart-contract/lib/Networks.ts' is not a module.    

2 import { ethereumTestnet, ethereumMainnet } from '../lib/Networks';
                                                   ~~~~~~~~~~~~~~~~~
config/CollectionConfig.ts:3:25 - error TS2306: File 'C:/Users/jerome/Desktop/nft-erc721-collection-2.0.0/smart-contract/lib/Marketplaces.ts' is not a module.

3 import { openSea } from '../lib/Marketplaces';
                          ~~~~~~~~~~~~~~~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\jerome\Desktop\nft-erc721-collection-2.0.0\smart-contract> 

Any advice? im totally stuck

**Comment by hernan-gil** [comment]
Hi, can you put rename-contract script here?
thanks in advance
