### ISSUE TITLE
Minting dapp to personal website

### ISSUE THREAD

**Issue by casuallycurious** [hashlips-lab/nft-erc721-collection#153]
Hello, How do you add this minting dapp to a personal website? I've tried adding the code from index.html, but it comes up broken. When I run the command yarn build, it cannot find the .json file.

**Comment by casuallycurious** [comment]
I've been able to connect and older version of hashlips minting dapp to my website, but still unable to get this one to work. When opening the website the title YOUR_AWESOME_NFT_COLLECTION appears in the tab, with a white page with the broken image symbol and the text: Logo
Please, any advice would be great :)

**Comment by ClubPEC** [comment]
@casuallycurious after running Build , just change the name to mint.html or whatever page you've created then upload it to your FTP client.
You need to change the Name & Images in your minting-dapp

**Comment by casuallycurious** [comment]
@ClubPEC Thank you for your help! Am I changing the name of the whole folder "build" or html files? I've update the file index.html to my website address. I now receive:
Error 403 - Forbidden
You tried to access a document for which you don't have privileges.

I'm going to keep trying, to see if i missed something.. any further assistance is greatly appreciated

**Comment by casuallycurious** [comment]
Hello again,

I'm running into the same problems, I've renamed the html file, it doesn't work. I have no issues with hashlips_nft_minting_dapp hosting on my website. After I run build on the original minting dapp I receive this:

7 files written to public/build
Entrypoint main [big] 770 KiB = main.css 14.8 KiB main.js 756 KiB
Entrypoint _tmp_copy (127 KiB) = 3 auxiliary assets
webpack compiled successfully

When I run build on the minting-dapp included in the ERC721a contract I receive the same:

7 files written to public/build
Entrypoint main [big] 770 KiB = main.css 14.8 KiB main.js 756 KiB
Entrypoint _tmp_copy (127 KiB) = 3 auxiliary assets
webpack compiled successfully

I have done everything the same when it comes to hosting it on my website, but only the first minting-dapp works.. 

Please help

**Comment by casuallycurious** [comment]
![Screen Shot 2022-03-23 at 1 17 04 AM](https://user-images.githubusercontent.com/98852050/159654409-7aad460d-517c-4b64-a351-c227f8ac340e.png)

Here is an Image of the build folder

**Comment by casuallycurious** [comment]
@ClubPEC I have it all working now! Thank you again for all your help! It wasn't a problem with the code, or build process, it was a problem on my webspace host.

**Comment by ClubPEC** [comment]
Glad everything worked out for you . No need to thank mate . We all are new in this space and every little help matters.

Good luck with your project .

Thanks 
PEC

**Comment by liarco** [comment]
Thank you very much for your help @ClubPEC.

**Comment by elGuille** [comment]
off topic but how would you host this to potentially be able to accept thousand of visits?

**Comment by elGuille** [comment]
@casuallycurious may I know what host you using? Thank you and thank you also to @ClubPEC  and of course @liarco
