### ISSUE TITLE
Gas fee problem

### ISSUE THREAD

**Issue by hrnft** [hashlips-lab/nft-erc721-collection#154]
When using the minting dapp, Connect wallet > Mint > Metamask transaction pops up > The confirm transaction button is null and until you hit > Market and select a gas type low / med / high ... it will not allow you to make the mint/transaction without selecting the Market link?

**Comment by liarco** [comment]
Hi @hrnft, I think you enabled the [new Gas Fees UI](https://metamask.io/1559/) from MetaMask. We are not doing anything strange on the DAPP side... I'm afraid there is nothing we can do about it, that's a new thing and I think you can disable it from the settings.
