### ISSUE TITLE
Wallet Connect Feature?

### ISSUE THREAD

**Issue by thefreshlab** [hashlips-lab/nft-erc721-collection#155]
is it possible to implement wallet connect feature with this version?
I noticed there are references and script replacements for the main redux version - but these scripts dont exist in this version.

**Comment by liarco** [comment]
Hi @thefreshlab, the DAPP used by this project has been rebuilt from scratch so no previous feature can be ported easily from the old HashLips version. I'm considering supporting WalletConnect in the future but I have many concerns with that protocol so there is no plan to work on this anytime soon.

Anyway I'm gonna take this suggestion into consideration. Thank you very much for your feedback!

**Comment by jvel07** [comment]
Hi @liarco! Hoping you are doing amazing!

 I came across this question and was wondering whether is there any code shared to implement wallet connect?
Or in turn, to have Coinbase Wallet feature?

**Comment by liarco** [comment]
Hi @jvel07,
I supported a couple of [Open Devs Crew](https://opendevs.io) members with this so far, but we didn't have time to work on any public release yet.
