### ISSUE TITLE
Minting Dapp not working on mobile phones

### ISSUE THREAD

**Issue by jan10101** [hashlips-lab/nft-erc721-collection#159]
Hi, 

I noticed the minting app is working fine on desktop but not on mobile phones. On mobile phones it just tells me that metamask is not installed. Same issue in all browsers (chrome, safari etc.). Are there plans to improve this in future versions or Is there a way to fix this or is there a workaround?

![IMG_0543](https://user-images.githubusercontent.com/810919/159441740-24aae5b4-1b9f-43c7-afb7-e3fcc5caa1e7.PNG)

**Comment by jan10101** [comment]
> Hi on mobile , instead of Safari or Android browser, use Metamask in built browser and type in your minting dapp webpage address. Works perfect.

I know. But I think most users don't know. Would be nice if instead of showing some confusing error message, it would be nice if the connect button could open metamask automatically or something.

**Comment by ClubPEC** [comment]
Simple solution is to Inform your users via your minting dapp . You can write instructions in same warning how to connect on mobile. Just educate the users. 

You can change the wording in your Minting-Dapp .

Thanks

**Comment by casuallycurious** [comment]
Thank you for this advice!

**Comment by liarco** [comment]
I totally agree with @ClubPEC. There is a contribution (#179) that implements something like this, but I'm still not sure about the UX. Until we find a better way I highly suggest customizing the message or explaining the users how they are supposed to use their wallets (no DAPP is gonna work with MetaMask outside of the in-app browser on iOS so they should know it).

**Comment by basememara** [comment]
I got draft PR #292 started that integrates [RainbowKit](https://www.rainbowkit.com) which handles mobile flow and multiple wallets. Issues to be worked out but looking for help there if anyones interested.
