### ISSUE TITLE
Help - How can I offer Free NFTs in Presale stage ?

### ISSUE THREAD

**Issue by ClubPEC** [hashlips-lab/nft-erc721-collection#160]
Dear Marco

Ciao , Hope you are well. its not an issue but kind of help i need.

I want to offer some tokens for free in presale stage . How can i do it ?

Do I have to re deploy the contract with new 00 price ? or i can simply write in contract in set price section ?

Thanks 
PEC

**Comment by liarco** [comment]
Hi @ClubPEC,
Prices for pre-sale and public sale are set once you open them. So feel free to change the settings in your config file before you open the sale... if you already opened it, you can simply run the `yarn pre-sale-open ...` again after you changed the config.

**Comment by ClubPEC** [comment]
Hi Marco
  
  
   
  
  
   Thank you for reply. I will give it a try and let you know if it works.
  
  
   
  
  
   Thanks 
  
  
   
    On 29/03/2022 17:08 Marco Lipparini ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Hi @ClubPEC,Prices for pre-sale and public sale are set once you open them. So feel free to change the settings in your config file before you open the sale... if you already opened it, you can simply run the yarn pre-sale-open ... again after you changed the config.
