### ISSUE TITLE
I am trying to set cost while deploying contract , it is giving me following error!

### ISSUE THREAD

**Issue by Wajid4040** [hashlips-lab/nft-erc721-collection#165]
transact to YourNftToken.setCost errored: Error encoding arguments: Error: invalid BigNumber string (argument="value", value="0.1", code=INVALID_ARGUMENT, version=bignumber/5.5.0)

**Comment by liarco** [comment]
Hi @Wajid4040 can you please share the following section of your configuration file?
https://github.com/hashlips-lab/nft-erc721-collection/blob/bf6680d5b19c1aed38c92933ea837fc13e342d98/smart-contract/config/CollectionConfig.ts#L17-L28

**Comment by liarco** [comment]
Closing this since I received no feedback. The error also seems related to a bad configuration I highly suggest taking a look at [my video tutorials](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials) on how to use this tool in order to avoid this kind of issues.
