### ISSUE TITLE
Setting presale and whitelist cost after deployement + free mint for contract owner/deployer/certain addresses

### ISSUE THREAD

**Issue by Lypheal** [hashlips-lab/nft-erc721-collection#167]
Title Pretty Much explains what's the error+feature we need.

1. There isn't any function to set presale and whitelist cost after we deploy the contract, that should be implemented in my opinion.
2. Adding a function for free minting for contract owner/deployer or certain address would help a lot.

**Comment by CryptoShazzy** [comment]
1. You can change the costs for WL, Presale and public sale by updating the collectionconifg.ts file, and then running the appropriate script.
2. you can mint for free using the mintForAddress function directly from the contract. It allows you to mint to the owners address, or any address you choose.

**Comment by liarco** [comment]
As already said by @CryptoShazzy (thank you for your help): those features are already available so I'm gonna close this.

Thank you.
