### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Longshoreking** [hashlips-lab/nft-erc721-collection#169]
When trying to install truffle in the terminal it says permission denied. How do i go about fixing this???

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stevenanthony/.npm/_logs/2022-03-24T01_54_20_987Z-debug.log
stevenanthony@Stevens-Air ERC 721 WhiteList Contract % node -v
v14.17.3

**Comment by Bebeez** [comment]
i tried with adding sudo before the command and it works

**Comment by Longshoreking** [comment]
it asks me for a password now when i add that before the command. didnt know a password would be needed lol

> i tried with adding sudo before the command and it works

**Comment by Longshoreking** [comment]
thanks the issue is fixed now!
