### ISSUE TITLE
Refunds from smart contract. 

### ISSUE THREAD

**Issue by Salro1g** [hashlips-lab/nft-erc721-collection#170]
Hi! 
Can someone tell me how I recover the eth from the smart contracr created? I mean, I'm using all time testnet, all works correctly but I see that the eth are in the smart contract not in the wallet that I have used.

**Comment by casuallycurious** [comment]
Hello, you can do this through etherscan, under account your smart contract was created on

**Comment by Salro1g** [comment]
Thx a lot!!
