### ISSUE TITLE
Enhancement: Gas free listing on Opensea

### ISSUE THREAD

**Issue by CryptoShazzy** [hashlips-lab/nft-erc721-collection#173]
Hi,

Have you considered adding the code to allow gas free sales on Opensea?

thanks

**Comment by basememara** [comment]
How would this work? From what I understand, you have to lazy mint on OpenSea by creating listings on their user interaface without even using a smart contract. It uses OpenSea's contract and Polygon and OpenSea buries the cheap Polygon gas fees in their commission fee. With that said, this repo does have a Polygon provider as one of the networks. Is there anything beyond this that you're looking for?

**Comment by CryptoShazzy** [comment]
It works by allowing OS to transact with the token contract through a proxy account, which proves ownership of the NFT. Whenever you list a new collection on OS, you generally have to pay a fee to carry this proof of identity out.  By including the proxy transaction in your contract, when the owner of the NFT goes to list, the identity is already proven through the proxy and there is no fee involved for your owners.
