### ISSUE TITLE
Whitelist Specific Limits

### ISSUE THREAD

**Issue by allendp11** [hashlips-lab/nft-erc721-collection#174]
Anyone have an idea of how to set specific limits to each whitelist address?
In example

I want whitelist address 1 to be able to mint 4 nfts.
I want whitelist 2 to be able to mint 7 nfts.

and so son...

**Comment by liarco** [comment]
Hi @allendp11, there is no simple way to achieve this with the current implementation. I'm thinking about something like this for a next version, but I have nothing ready yet (and I'm not 100% sure I can find an efficient way to do this).

You might find some help (or you can hire a developer) on the HashLips' discord server. 😉
