### ISSUE TITLE
Withdraw Function 

### ISSUE THREAD

**Issue by 0kt4y** [hashlips-lab/nft-erc721-collection#177]
please teach us how to add Withdraw Function  to contract

**Comment by basememara** [comment]
There already is a withdraw function on the contract: https://github.com/hashlips-lab/nft-erc721-collection/blob/bf6680d5b19c1aed38c92933ea837fc13e342d98/smart-contract/contracts/YourNftToken.sol#L154

You can go to etherscan.io and execute the write function as the owner.
