### ISSUE TITLE
Yarn Install Issue inside the Smart-Contract Folder

### ISSUE THREAD

**Issue by Valhcolletion** [hashlips-lab/nft-erc721-collection#18]
Hi there I am trying to Install the dependencies into the smart-contract folder and I am unable to it completes about 2 and then I get this error message if someone could help me that would be great. (couldn't find the binary git)

![Capture](https://user-images.githubusercontent.com/100174533/155045637-e7e43857-2b21-4b9b-ba52-8728774180ff.PNG)

**Comment by liarco** [comment]
Hi @Valhcolletion, please see #5.
