### ISSUE TITLE
Secondary sales

### ISSUE THREAD

**Issue by justinsteu** [hashlips-lab/nft-erc721-collection#181]
Does this smart contract have a secondary sales royalty feature too it, or is that something that you would have to add when adjusting the code to your project?

I see the "royalty" section that goes to Hashlips at the bottom of the contract, but I haven't seen anything that enables the artist to receive royalties from secondary sales.

Thanks.

**Comment by liarco** [comment]
Hi @justinsteu, please take a look at some of the issues already covering this topic: https://github.com/hashlips-lab/nft-erc721-collection/issues?q=royalties

Thank you.
