### ISSUE TITLE
Withdrawl Error: We were not able to estimate gas. There might be an error in the contract and this transaction may fail.

### ISSUE THREAD

**Issue by h0rizons** [hashlips-lab/nft-erc721-collection#183]
When trying to call the Withdraw function I keep getting the following error with EXTREMELY high gas:

`We were not able to estimate gas. There might be an error in the contract and this transaction may fail.`

I had tested the contract on Rinkeby prior to using it on the mainnet, and was able to withdraw perfectly fine.

I double + triple checked that I was using the owner address when trying to call withdraw.

Any help would be greatly appreciated. <3

**Comment by h0rizons** [comment]
<img width="734" alt="Screen Shot 2022-03-29 at 11 44 49 PM" src="https://user-images.githubusercontent.com/100657102/160761457-1c8b8c5a-4d47-4942-a58d-be6c9fea92b5.png">

**Comment by h0rizons** [comment]
<img width="734" alt="Screen Shot 2022-03-29 at 11 44 49 PM" src="https://user-images.githubusercontent.com/100657102/160761499-b2ce6423-260e-4ba7-8fdb-8065526be6a5.png">

**Comment by h0rizons** [comment]
<img width="1352" alt="Screen Shot 2022-03-30 at 12 03 40 AM" src="https://user-images.githubusercontent.com/100657102/160762506-090ee5d8-6a8f-43f9-838a-cdb71cb7912d.png">

I tried setting the gas manually but got this error as well.

**Comment by h0rizons** [comment]
https://etherscan.io/tx/0x9e3456d188c279739ed2953e171dadc74738874902168b417551b74a166cdf7f

**Comment by Salro1g** [comment]
Do you have enough Eth in your wallet to pay the transaction?

**Comment by Salro1g** [comment]
Mmmm, interesting. I have tested the script only on rinkeby net and it worked fine. Maybe tomorrow I will test on the mainet, so if I can run all fine or not I will tell you.

**Comment by h0rizons** [comment]
> Mmmm, interesting. I have tested the script only on rinkeby net and it worked fine. Maybe tomorrow I will test on the mainet, so if I can run all fine or not I will tell you.

The withdraw seemed to work fine on Rinkeby: https://rinkeby.etherscan.io/tx/0x0e78e3f962d2001956d039b317102a0e0ff6b77434ced4e8cbc206277b41012b

And like I said, I've launched another collection and experienced absolutely no issues with it whatsoever until with this one.

**Comment by h0rizons** [comment]
Is it possible that it worked on Rinkeby on not the Mainnet because:

The owners wanted me to put in a 5% payout to the Quirkies smart contract (not an actual address) - which on Rinkeby probably isn't a real smart contract, but on the Mainnet it is - do you think the issue is arising from the contract not being able to withdraw the 5% to a smart contract?

**Comment by h0rizons** [comment]
> Mmm, I don't think so. The script for the 5% is precisely a %, not a quantity of eth specifically. So if you withdraw a 0.1 eth they will recieve 0.005 eth. 

Understood. I meant the fact that I used an actual smart contract address in the payout, other than a regular ETH address. Could that be the cause or concern? 

Any help sorting this out would be greatly appreciated, and I will happily have the team send funds to compensate for a successful withdrawal.

**Comment by fullStackRyan** [comment]
Hey, 

I had the same problem but solved it. 

My issue was that I connected the account which set up the Etherscan with and not the account which created the contract. 

Whatever MetaMask Wallet account you deployed the contract with, is the same one you have to use to withdraw

**Comment by liarco** [comment]
@h0rizons I'm so sad to say that those funds might be stuck forever.

You can't send ETH to a contract which doesn't implement a `fallback` or a `receive` function, so the withdraw function is probably failing because of that. Here is the doc about this: https://docs.soliditylang.org/en/latest/contracts.html#special-functions

I'm sorry but since you can't change either contracts, I think there will never be a way to withdraw those funds.

I have to close this since it's not related to the project and I doubt anyone can come up with a solution... 😥
