### ISSUE TITLE
How do you withdraw? 

### ISSUE THREAD

**Issue by fullStackRyan** [hashlips-lab/nft-erc721-collection#184]
I'm doing final test run on Rinekby and following along with this tutorial: https://www.youtube.com/watch?v=Zhmj4PiJ-GA&t=3048s

I cannot see the command in package.json for withdrawing the Eth?

<img width="447" alt="Screenshot 2022-03-30 at 07 18 42" src="https://user-images.githubusercontent.com/59806496/160764308-342e12c2-a5bb-4510-a28d-929778321d99.png">
 
 I also tried to do it via etherscan but got the above error, despite connect my meta mask. 
 
 Any help would be greatly appreciated.

**Comment by Salro1g** [comment]
If you connect via etherscan testnet your wallet it is easy to do.

**Comment by fullStackRyan** [comment]
Hey mate, 

Thanks for the reply, I missed one of the small button where it says connect. Thanks for the reply
