### ISSUE TITLE
Reveal function can't find deployed contract

### ISSUE THREAD

**Issue by rawkfist2022** [hashlips-lab/nft-erc721-collection#185]
Hello @liarco;
I greatly appreciate this incredible project you have put together. I was working on Rinkeby and have been able to get the whitelist, presale, and public sales to all open and close (multiple times). However, when I run the 'yarn reveal' command I end up with the following error:

error Can't find a contract deployed to the target address: 0x1564118707Ebb11BA1068A5E01C559Da3f67886d

I'm not sure why this is happening only for the reveal command. Everything else has worked great. I was able to mint under the whitelist and the public sale (even with a second rinkeby account) and all mints showed up on Opensea test network. So I'm at a loss as to where to look to determine why the reveal command can't find the contract while the other commands do.

Thanks!

**Comment by Salro1g** [comment]
Hi! 

The script works correctly so you will need to watch step by step your work. Did you put the JSON correctly? I mean, you need 2 different metadata files, one for Hidden and one for the collection. 
Tell us.

**Comment by rawkfist2022** [comment]
Yes, I have used the hidden data and in the .env file placed the real Metadata. I've previously run this with another set and the reveal function worked, but I had messed something up with my addresses. This time, the reveal function can't find the contract to even perform it. I've followed the Hashlips masterclass video on YouTube and performed all the steps. So I'm not sure why it isn't working for me today.

**Comment by Salro1g** [comment]
Did you use a different API Key and New project in Infura?

**Comment by rawkfist2022** [comment]
No. It was the same API key.

**Comment by rawkfist2022** [comment]
Okay. I will work on that later and try it again. But I was sp close on this project. I dont want to do this on my main ETH account until I can do this in my sleep with no errors.

**Comment by liarco** [comment]
Hi @rawkfist2022 this error usually happens when you try to run a command on the wrong network (so the app cannot find the given contract there).

Are you completely sure you are running the command while being connected to Rinkeby?

**Comment by cryptocraig-nft** [comment]
> Hello @liarco; I greatly appreciate this incredible project you have put together. I was working on Rinkeby and have been able to get the whitelist, presale, and public sales to all open and close (multiple times). However, when I run the 'yarn reveal' command I end up with the following error:
> 
> error Can't find a contract deployed to the target address: 0x1564118707Ebb11BA1068A5E01C559Da3f67886d
> 
> I'm not sure why this is happening only for the reveal command. Everything else has worked great. I was able to mint under the whitelist and the public sale (even with a second rinkeby account) and all mints showed up on Opensea test network. So I'm at a loss as to where to look to determine why the reveal command can't find the contract while the other commands do.
> 
> Thanks!

Hey Dude, I know this might sound stupid but are you typing the command properly "yarn reveal --network truffle" I was having the same issue when I realised I was typing "yarn reveal", think I've been in front of the screen to long! Anyway good luck!

**Comment by rawkfist2022** [comment]
OH MY FREAKING WORD! I had written down all my commands and didn't have "--network truffle". It worked!
Thank you everyone for all the help!!!
