### ISSUE TITLE
VS error in comand npm i -g truffle 

### ISSUE THREAD

**Issue by Zaffon** [hashlips-lab/nft-erc721-collection#188]
every time i run command line specified i receive error code in attached , i have installed python link , install node gyp ? can any one help
[NFT - ERC error.txt](https://github.com/hashlips-lab/nft-erc721-collection/files/8383648/NFT.-.ERC.error.txt)

**Comment by lakeofthewoods1** [comment]
I am having the same issue. Can some one help?

**Comment by liarco** [comment]
Hi, this error is explained in my video about [how to setup your Windows 10 machine](https://youtu.be/zjlg-0622PU). Please make sure to follow all the steps carefully.

**Comment by Zaffon** [comment]
Thanks I'm running windows 11 so I will check your setup instructions
