### ISSUE TITLE
Unsupported network!

### ISSUE THREAD

**Issue by Angrywolvesdev** [hashlips-lab/nft-erc721-collection#191]
Hello, when I try to implement it in the network of polygons I get an error in the Dapp "Unsupported network!", really what I want to do is simply lie the entire collection in **Opensea** and make purchases there directly, I have already created the contract the only thing what is missing is the mint, what I had planned to do is use the dapp to mint the entire collection, I would put a very minimum price and the maximum amount to mint them all, could this be done in another way? or how do I resolve the **_Dapp error?_** Thank you

**Comment by Reptiliian** [comment]
if you want to mint the whole collection your self you can just mint trough the contract it self. it will automatically be uploaded to OpenSea

**Comment by Angrywolvesdev** [comment]
definitely what I need, how can I do it?  thanks for your answer 🙏🏼

**Comment by Angrywolvesdev** [comment]
If anyone else has this problem check out @liarco's video on project setup https://youtu.be/pkA86GHU_xw
