### ISSUE TITLE
contract verified on rinkeby but failed on ETH mainnet 

### ISSUE THREAD

**Issue by lbastian10** [hashlips-lab/nft-erc721-collection#194]
Hi im been trying to verify my contract on ETH mainnet for always failed but the same contract worked fine and was verified on rinkeby

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

thanks

**Comment by Salro1g** [comment]
Do you have enough eth to pay the gas and the contract for your collection?¿

**Comment by liarco** [comment]
Hi @lbastian10, please avoid posting the same question multiple times. I already answered [here](https://github.com/hashlips-lab/nft-erc721-collection/issues/83#issuecomment-1086427998).

About the mainnet appearing "red" that's correct. The main network is shown as red as a warning so the user knows that he must pay attention to what he is doing.

Also verifying the collection doesn't cost anything, so you don't need any ETH for this.

Please reply here if you need any further help with this.

**Comment by lbastian10** [comment]
thank you for your response,  

probably thats what happening that i update some dependency or something but it was cause the couple of times that i tried verifying failed so i was trying to fixit.

i've been trying so many thing but always failed, even manually verification.
![Screen Shot 2022-04-02 at 1 24 41 PM](https://user-images.githubusercontent.com/102747539/161394332-f727a958-e58e-4baf-b04e-8fe9b5da1df0.png)


what would you recommend ? to make a new fresh contract 

thank you so much

**Comment by liarco** [comment]
@lbastian10, I'm sorry but trying to get back to the original code you had when you deployed the contract might cost you more than deploying again.

If your only option is to deploy again, then here is what I suggest:
1. start from a brand new project folder
2. install all dependencies and make sure everything is working correctly
3. make all the changes to the configuration as explained in my videos
4. deploy and verify on the testnet without touching any file in your project
5. make sure everything works fine on the testnet
6. reset the `contractAddress` value in your configuration
7. deploy to the mainnet
8. update the contract address
9. verify immediately without changing any file

I hope this helps.
