### ISSUE TITLE
Have there been updates?

### ISSUE THREAD

**Issue by rawkfist2022** [hashlips-lab/nft-erc721-collection#196]
Have there been updates to certain packages that have led to a broken code? I see things like:
warning " > @typechain/ethers-v5@7.2.0" has unmet peer dependency "@ethersproject/bytes@^5.0.0".
warning " > @typechain/ethers-v5@7.2.0" has unmet peer dependency "@ethersproject/providers@^5.0.0".
warning " > @typechain/ethers-v5@7.2.0" has unmet peer dependency "@ethersproject/abi@^5.0.0".
warning " > @typechain/hardhat@2.3.1" has unmet peer dependency "lodash@^4.17.15".
now when I'm loading my yarn dependencies that I haven't seen previously. Could explain why now I'm not able to obtain the right bytes and abi when trying to verify?
Thanks.

**Comment by Salro1g** [comment]
When I use a new repository and I add yarn, both to smart-contract and minting-dapp folders works correctly.

**Comment by rawkfist2022** [comment]
Which new repository? Re-downloadong the nft-erc721-collection or updating the dependencies?

**Comment by Salro1g** [comment]
Try to re-download the repository and turn to install yarn dependencies. Sometimes when something is wrong, reinstall is the possible solution.

**Comment by liarco** [comment]
Hi @rawkfist2022 "peer dependencies" are not strictly required. You get that notification but it's a "warning", not an "error". It's perfectly fine since we are not using those libraries.

The reason why the package manager tells you about that, is because the packages we depend on are suggesting using them because they might be useful in many cases... but we don't need them.

I hope this helps.

**Comment by rawkfist2022** [comment]
Sorry, I've had a busy couple of days and haven't been able to get everything tested again. 
This time (after downloading the file again), I didn't even have to verify the contract...it 'auto-verified' (if that is even a thing) right after deployment. Either way, I was able to complete whitelisting and revealing this time. 
Thank you so much @liarco and @Salro1g for all your help in getting this running for me! This is a great system you've created for us novice people.
