### ISSUE TITLE
'sudo' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by astrosaylor** [hashlips-lab/nft-erc721-collection#2]
Hi,

I started with "How to create an NFT collection - Ultimate guide" and now with my artwork done it's time to go futher.
Follow all your steps but got this error and don't know how to fix it.

![Screenshot 2022-02-17 232757](https://user-images.githubusercontent.com/91560189/154588763-c1d156a4-bb57-434c-82ee-2c65de334d97.png)

Internal Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\pnpm'
Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\pnpm'
PS C:\Users\Vasco\Desktop\nft-erc721-collection-1.0.0> sudo corepack enable
>>
sudo : The term 'sudo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ sudo corepack enable
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (sudo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
    All the help is more than welcome.
    Thanks
    
    BTW What an awesome tool. Congratulations!

**Comment by liarco** [comment]
Hi, all users reporting such errors are probably using a non-UNIX operating system (maybe Windows?) or maybe you are using Linux distribution which is not Debian-based.

`sudo` (Super User DO) is a command-line utility that allows users to run the command that follows it as a super user (usually `root`). This should work on MacOS and any Debian-based Linux distribution.

For Windows machines, you can simply open your terminal as an Administrator (it should be something like `right-click > Run as Administrator`) and then you can simply run the command without the `sudo` prefix: `corepack enable`.

I hope this can help you solving the issue, please let me know so we can close this issue.

**Comment by liarco** [comment]
Closing this since we are not getting any feedback, but I'm pretty sure this can be solved with the instructions above.
