### ISSUE TITLE
Error in plugin @nomiclabs/hardhat-etherscan

### ISSUE THREAD

**Issue by lakeofthewoods1** [hashlips-lab/nft-erc721-collection#201]
Hi,

Thank you for helping before. I am at the point of verifying the contract with the command yarn verify and I get this error:

Successfully submitted source code for contract
contracts/MonarchGlider.sol:MonarchGlider at 0xd13EDB2D951a55EAC161cC7aa400acb91e7C73b0
for verification on the block explorer. Waiting for verification result...

We tried verifying your contract MonarchGlider without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/MonarchGlider.sol:MonarchGlider at 0xd13EDB2D951a55EAC161cC7aa400acb91e7C73b0
for verification on the block explorer. Waiting for verification result...

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\Downloads D\nft-erc721-collection-2.0.0\nft-erc721-collection-2.0.0\smart-contract>

I tried going through the links but I am not able to move on.

Thank you

**Comment by liarco** [comment]
Hi @lakeofthewoods1,
this issue is well explained in one of my [YouTube videos](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials). Here is the video at the exact timing: https://youtu.be/yOVKEeRMJSs?t=257
