### ISSUE TITLE
Using With Solana 

### ISSUE THREAD

**Issue by granthughes1999** [hashlips-lab/nft-erc721-collection#203]
Is it possible to use this set-up with Solana or would it require a large overhaul?

**Comment by liarco** [comment]
Hi @granthughes1999, thank you for joining us. Unfortunately Solana uses a completely different programming language, so this tool cannot be easily ported to that chain.

We might create something similar for it in the future, but there is no plan for that at the moment.

I hope you will have the chance to give this a try on any Ethereum-compatible chain. 😉
