### ISSUE TITLE
how to not show uriPrefix content being read in smart contract 

### ISSUE THREAD

**Issue by dcryptodev** [hashlips-lab/nft-erc721-collection#204]
Hi 

I was wondering how we go about not showing the uriPrefix content when someone is reading your smart contract?

In my smart contract in **Read Contract** the contract shows  uriPrefix URL of my collection which consists of my json files and within the json file the .png's of the NFT's

```
 18. uriPrefix
ipfs://QBLALALABALABLA/ string

```

The issue here by showing the URL Prefix readable and everyone can see it, people will be able to see the images of the collection already even  while you have **revealed** set to **false** as they can easily just go on ipfs.io/ipfs/BALALALALALALA/1.json to see your collections before you launch. Therefore this actually limits the value of a revealing the NFTs as people can already see the entire collection before the reveal is open 
Is there a way to hide the uriPrefix content directly on the smart contract ?

**Comment by liarco** [comment]
Hi @dcryptodev,
this is not a bug, this is how the blockchain works: everything is public. If you want to protect your metadata you can use some other tools like the [Safe NFT Metadata Provider](https://github.com/hashlips-lab/safe-nft-metadata-provider).
