### ISSUE TITLE
Added BlindBOX feature

### ISSUE THREAD

**Issue by Shiba-Matic** [hashlips-lab/nft-erc721-collection#217]
Added BlindBOX feature

This is my suggestion, when the user MINT blind box, can add a parameter, the user can choose to reveal the blind box immediately, and show the NFT data, or can wait for the public reveal. I think that's a good idea. Hope you can update.

    bool public blindBoxOpen;
    bool public useBlind;

    function setBlindBoxOpened() public onlyOwner {
        blindBoxOpen = !blindBoxOpen;
    }

    function setUseBlind() public onlyOwner {
        useBlind = !useBlind;
    }

 function tokenURI(uint256 tokenId) public view virtual override returns (string memory) {
        require(_exists(tokenId), 'ERC721Metadata: URI query for nonexistent token');

        if(useBlind) {
            if (blindBoxOpen) {
                string memory baseURI = _baseURI();
                return bytes(baseURI).length != 0 ? string(abi.encodePacked(baseURI, tokenId.toString())) : '';
            } else {
                return blindTokenURI;
            }
        } else {
            string memory baseURI = _baseURI();
            return bytes(baseURI).length != 0 ? string(abi.encodePacked(baseURI, tokenId.toString())) : '';    
        }
    }

**Comment by Shiba-Matic** [comment]
I think this feature is very necessary. Because they bought this NFT, they have the right to open it immediately, rather than waiting for the project side to slack off.

**Comment by liarco** [comment]
Sorry, but you opened a bug report, not a feature proposal. This kind of things [should be discussed here](https://github.com/hashlips-lab/nft-erc721-collection/discussions).

Thank you.
