### ISSUE TITLE
collectionConfig.ts file  doble quotation marks (")  or single quotation marks ( ' ) 

### ISSUE THREAD

**Issue by lbastian10** [hashlips-lab/nft-erc721-collection#219]
i seen in the collectionConfig.ts file  that everything it is between single dots in each side like this by default  

contractname:  ' example ' 

tokenName:   ' example '

tokenSymbol : ' ex '

hiddenMetadataUri: 'ipfs://example/hidden.json',

contractAddress: '0xA0000000000000000000000000000030',
  
marketplaceIdentifier: '0000-token',
 
thats these need to be in between of double dots ("      ") or its the same ?

cause i dont know if its the problem that the images dont show up in opensea test net or its just opensea 

thanks !

**Comment by liarco** [comment]
Hi @lbastian10, this is not a valid bug repost. Please follow the instructions carefully and use the [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions) for questions.

Thank you.
