### ISSUE TITLE
Error HH307: Missing positional argument address

### ISSUE THREAD

**Issue by rawkfist2022** [hashlips-lab/nft-erc721-collection#224]
### General information

| Project version | 1.1.2_patch_v6 |
| Operating system and version | Windows 10, 21H1 |
| NodeJS version | 16.14.0 |
| NPM version | 8.3.1 |
| Yarn version | 1.22.15|
| Truffle version | 5.5.7 |

### Describe the bug
Created a contract is on Etherscan in the Etherium Mainnet. Trying to verify the contract and it errors with:
Error HH307: Missing positional argument address
The contract is on Etherscan in the Etherium Mainnet. 
I have performed many practice ones on the rinkeby network and it worked just fine. So I don't know what is wrong. But I can't afford to try this multiple times.  I need to be able to verify this contract.

### Expected behavior
Should verify the contract.

**Comment by liarco** [comment]
Hi @rawkfist2022,
don't worry, you simply forgot to enter the contract address as also pointed out by the error: `Error HH307: Missing positional argument address`.

Please, next time include all the required information such as the commands you are running.

**Comment by rawkfist2022** [comment]
Hey @liarco 
I had the contract address in the CollectionConfig.ts and saved when I tried to verify the contract.
From the start I did:
npm i -g truffle (then truffle dashboard and connected to my metamask ETH wallet)
then in new terminal, npm i -g corepack
then yarn
then copy, pasted and changed the .env file with my metadata address and API key
then updated the whitelist.json with just my metamask account (that I was using with truffle)
then yarn rename-contract (with my contract name)
then changed and saved the CollectionConfig.ts with information (token name, max mint amount, ect)
then yarn deploy --network truffle
then copied and pasted in my new contract address, replacing the 'null' and saved the file
then yarn verify --network truffle and this is where I got the error. 

Is there anything I missed?

**Comment by liarco** [comment]
@rawkfist2022, I already answered above: you are missing the contract address in the verification command. Please pay attention to the instructions in the my videos:

```bash
yarn verify CONTRACT_ADDRESS_HERE --network truffle
```

I'm closing this since now it's clear that you are running the wrong command so there is no bug to be fixed.

**Comment by rawkfist2022** [comment]
Oh my word, am I that stupid!!
I'm so sorry!!
Thank you!!!!
