### ISSUE TITLE
How much gas for the deployment?

### ISSUE THREAD

**Issue by GoodGoldDev** [hashlips-lab/nft-erc721-collection#23]
Hi there again, while publishing to the main network,... any idea how much time that takes and gasfee?
I will know in a few minutes, but I was just wondering If I had enough in my wallet.

It says: No need to generate any newer typings ... 
... for a few minutes now, but I guess I have to be patient.

Kind Regards,

Roemer.

**Comment by GoodGoldDev** [comment]
Still busy... 20 minutes...

**Comment by GoodGoldDev** [comment]
1.30 hour 
But I do not dare to stop the process...

**Comment by liarco** [comment]
Hi @GoodGoldDev,
I'm so sorry for the waiting but unfortunately I have no access to my computer right now so it's pretty hard for me to follow this issue. First of all I suggest you opening your own address on etherscan looking for pending transactions. If there's nothing there, it should be safe to stop the process.
The command makes a gas estimation using the web3 provider (Infura if you followed the videos) so it should fail with an error before sending the transaction if you don't have enough ETH to complete it successfully. Anyway something bad might always happen (even simple network issues).

I'm gonna add information to this as soon as possible.

**Comment by GoodGoldDev** [comment]
No problem! I'm getting a time out. So will try again with more ETH. Thanks for the advice!

**Comment by liarco** [comment]
Yes, please make sure you are using the correct Infura endpoint (the HTTPS one and for the right network). If all of that is correct, then you should be fine.

Let me know if you finally succeeded.

**Comment by GoodGoldDev** [comment]
It worked this morning. 08.00 Amsterdam time. It costed me 0.262 ETH. to deploy.

**Comment by liarco** [comment]
Happy to hear that. That's not bad as price for deployment.

Best of luck for your project!
