### ISSUE TITLE
Is there a safe way to remove the single whitelist claim requirement?

### ISSUE THREAD

**Issue by joven1555** [hashlips-lab/nft-erc721-collection#246]
Hi Liarco & Team:

I'm very hesitant to make changes to the SC, but we would like to remove the requirement that a whitelisted user can only make 1 transaction.  Here is the original and then my suggested edits.  Any feedback would be immensely appreciated.  Also would the 'bytes32[] calldata _merkleProof' be removed at the top?  I don't think so, and it should just be whitelistClaimed functions.  It also doesn't seem like there are any changes necessary in other places of the SC.

### ORIGINAL
```
  function whitelistMint(uint256 _mintAmount, bytes32[] calldata _merkleProof) public payable mintCompliance(_mintAmount) mintPriceCompliance(_mintAmount) {
    // Verify whitelist requirements
    require(whitelistMintEnabled, 'The whitelist sale is not enabled!');
    require(!whitelistClaimed[_msgSender()], 'Address already claimed!');
    bytes32 leaf = keccak256(abi.encodePacked(_msgSender()));
    require(MerkleProof.verify(_merkleProof, merkleRoot, leaf), 'Invalid proof!');
    whitelistClaimed[_msgSender()] = true;
    _safeMint(_msgSender(), _mintAmount);
  }
```
Also at the top exists:    mapping(address => bool) public whitelistClaimed;

### SUGGESTED CHANGE
```
 function whitelistMint(uint256 _mintAmount, bytes32[] calldata _merkleProof) public payable mintCompliance(_mintAmount) mintPriceCompliance(_mintAmount) {
    // Verify whitelist requirements
    require(whitelistMintEnabled, 'The whitelist sale is not enabled!');

    bytes32 leaf = keccak256(abi.encodePacked(_msgSender()));
    require(MerkleProof.verify(_merkleProof, merkleRoot, leaf), 'Invalid proof!');

    _safeMint(_msgSender(), _mintAmount);
  }
```
Is it also safe to remove this at the top:    mapping(address => bool) public whitelistClaimed;

**Comment by liarco** [comment]
Hi @joven1555, please open this as a discussion and add a reference to this issue since this is not a valid bug report.
