### ISSUE TITLE
NFTs minted but not visible on OpenSea, although they are visible on polygonscan 

### ISSUE THREAD

**Issue by explorion** [hashlips-lab/nft-erc721-collection#266]
Hello,

So I deployed a project using this database on Polygon network. The problem I am facing is out of 800 NFTs mintined only 300 are visible on OpenSea. its been more than 2 weeks since the NFTs were minted.
The NFTs are visible in on polygonscan in the token page as well as in the holders section but it is not visible on opensea in the collection page or in the wallet of owners.

Please guide. thank you

**Comment by Garryy26** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by explorion** [comment]
> Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

@liarco please block this guy, the link is false link & he is collecting wallet seed phrases through the site. 
This is polygon's actual forum link.
https://forum.polygon.technology/

Guys please don't click on such links & enter any confidential details

**Comment by liarco** [comment]
Thank you @explorion for reporting this. I reported the abuse to GitHub and I will block the user ASAP.

I'm sorry for this.

**Comment by explorion** [comment]
> Hello,
> 
> So I deployed a project using this database on Polygon network. The problem I am facing is out of 800 NFTs mintined only 300 are visible on OpenSea. its been more than 2 weeks since the NFTs were minted. The NFTs are visible in on polygonscan in the token page as well as in the holders section but it is not visible on opensea in the collection page or in the wallet of owners.
> 
> Please guide. thank you

Thank you @liarco can you also please help me find a solution to the issue. is it a problem with the repository or something else?

**Comment by liarco** [comment]
Hi @explorion, how did the tokens get minted? Did you batch mint a high number of tokens at once? That is known to be problematic on OpenSea.

I'm pretty sure the contract is fine (as you also verified on the block explorer), but OpenSea gets out of sync very often on Polygon.

**Comment by explorion** [comment]
@liarco I had batch minted 200 in one go & then in batches of 5, the NFTs are visible on block explorer but not on OpenSea.
what is a possible solution for this? Also do you know any other marketplace where the NFTs will be visible & can be made available for trade?

**Comment by liarco** [comment]
I'm sorry @explorion but I was in a rush and I just noticed this is an issue. Issues must be used for bug reports only (and they must follow the instructions you find in the template).

For this kind of things you should use the [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions) (there is also pinned discussion about this exact topic).

Thank you for your understanding.
