### ISSUE TITLE
feat: limit max supply per sale type

### ISSUE THREAD

**Issue by jdunham2** [hashlips-lab/nft-erc721-collection#269]
### Feature Request
Would like to be able to set the `maxSupply` based on the sales type. For example with a total maxSupply of 10000 we would like to only sell 2500 during a whitelist sale.

```
...
maxSupply: 10000,
  whitelistSale: {
     price: 0.001,
     maxMintAmountPerTx: 1,
     saleMaxSupply: 2500
  },
...
```

Alternatively, perhaps it would be more powerful to add a public method to allow to update the `maxSupply` after deploying the contract.

**Comment by liarco** [comment]
Hi @jdunham2 this is an invalid bug report, pleas use the Discussions section for this. Thank you. ;)
