### ISSUE TITLE
Error HH100

### ISSUE THREAD

**Issue by Valhcolletion** [hashlips-lab/nft-erc721-collection#27]
When trying to deploy to rinkeby I get an error message stating 
Error HH100 Network rinkeby doesn't exist 
Please help I have to deploy soon!

**Comment by liarco** [comment]
Hi @Valhcolletion,
that error means the Hardhat is not recognizing the network passed to the `--network` option.
The setup process for that network is skipped when the configuration for it cannot be found:

https://github.com/hashlips-lab/nft-erc721-collection/blob/d7006cdb1ce299bdf5870fffb0e888821e5bcaa5/smart-contract/hardhat.config.ts#L107-L113

My only way of reproducing this error is by doing one of these mistakes:
1. no `.env` file
2. missing (or commented out) `NETWORK_RINKEBY_URL` in `.env`

Please make sure you are following all the steps in our video correctly.
