### ISSUE TITLE
Error running yarn dev-server from command line

### ISSUE THREAD

**Issue by stevenliriano** [hashlips-lab/nft-erc721-collection#275]
### General information
| Description | Value |
| --- | --- |
| Project version | 2.3.0 |
| Operating system and version | OS 12.2.1 |
| NodeJS version | 14.8.2 |
| NPM version | 8.9.0 |
| Yarn version | 1.22.17 |
| Truffle version | 5.5.13 |

### Describe the bug
Receiving the following error and failing with exit code 1 when trying to run `yarn dev-server`: `Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
`
### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):
1. Run `yarn dev-server` from terminal while in the /minting-dapp directory

### Expected behavior
Command runs successfully as shown in the second screenshot below (pulled from the HashLips youtube tutorial titled "How to create an NFT collection - Masterclass")

### Screen
<img width="1058" alt="Screen Shot 2022-05-08 at 12 39 17 PM" src="https://user-images.githubusercontent.com/53834486/167308686-948d6a1b-322e-4c47-b67a-e65fb296bafa.png">

![Screen Shot 2022-05-08 at 12 42 36 PM](https://user-images.githubusercontent.com/53834486/167308692-cc31db19-a7b4-4079-bed6-973a63808f0a.png)

**Comment by liarco** [comment]
Hi @stevenliriano, thank you for your report. The command is actually working fine, that error message means that you already have a background service listening on port `8080` so the dev server can't bind to it. You can either stop the other service (highly recommended) or use custom port with `yarn dev-server --port 8081` (or any other port number).

Let me know if that solves the issue.

**Comment by liarco** [comment]
@stevenliriano it should be an HTTP service so you may browse http://127.0.0.1:8080, that might help understanding what it actually is. I don't have any better solution to be honest.

I'm gonna close this but let me know if it works 😉

**Comment by liarco** [comment]
@stevenliriano The IPFS daemon is supposed to spawn a web interface on that port so it will be up as long as you keep it running. It's important to know what is using that port (sometimes you run the dev-server twice and you are not aware of it), but if you are using that service, then there is no need to kill it.

In your case I think it's fine to simply use another port for the dev-server.

**Comment by liarco** [comment]
You are welcome! ;)
