### ISSUE TITLE
Verify Contract Error

### ISSUE THREAD

**Issue by sdcr8s** [hashlips-lab/nft-erc721-collection#283]
### General information
| Description | Value |
| --- | --- |
| Project version | 2.0.0 |
| Operating system and version | Mac Monterey 12.3.1|
| NodeJS version | 14.18.2 |
| NPM version | 6.14.15|
| Yarn version | 6.14.15 |
| Truffle version | 5.5.13 |

### Describe the bug
Followed Master Class steps fully. Installed perfectly.. When verifying the contract get this error..

Error in plugin @nomiclabs/hardhat-etherscan: Please provide an Etherscan API token via hardhat config. For example:

{
  ...
  etherscan: {
    apiKey: {
      rinkeby: 'your API key'
    }
  }
}

See https://etherscan.io/apis

### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):
Verify contract

**Comment by sdcr8s** [comment]
User error! Sorry Thank you for creating this!

**Comment by xman86** [comment]
how did you fix this?
