### ISSUE TITLE
Unable to Verify (HeadersTimeoutError)

### ISSUE THREAD

**Issue by AlphaBears** [hashlips-lab/nft-erc721-collection#289]
### General information
| Description | Value |
| --- | --- |
| Project version | 2.3.0 |
| Operating system and version | OS Montery 12.1 (21C52)|
| NodeJS version | v16.14.0|
| NPM version | 8.3.1 |
| Yarn version | 1.22.15 |
| Truffle version | 0.0.0 |

### Describe the bug

I keep getting the following error when trying to verify this contract:

```
$ hardhat verify --constructor-args config/ContractArguments.ts 0x990D962CA2Ee5Aed940483E5c9A9aC14Ca9e7C86 --network truffle
An unexpected error occurred:

HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/Users/timemachine/Desktop/bears/smart-contract/node_modules/undici/lib/client.js:1005:28)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
error Command failed with exit code 1.

```

### Expected behavior
Verifying the ERC-721A contract.

**Comment by liarco** [comment]
Hi @AlphaBears,
was Truffle Dashboard open when you run the command? which network were you verifying on? (eth mainnet, rinkeby, polygon, etc.). I looks like your CLI cannot connect to truffle or the block explorer correctly.

**Comment by wee4050** [comment]
Hi, I also encountered a problem while validating the contract.
![123](https://user-images.githubusercontent.com/96134975/173986314-e99c8d97-1e5d-481a-b25f-9509a93b8b9d.png)

**Comment by liarco** [comment]
@wee4050 I'm sorry but that screenshot looks really strange. None of my commands run the verification step right after deployment.

I'm closing this since I know for sure that @AlphaBears successfully verified the contract.
