### ISSUE TITLE
"Error HH100: Network rinkeby doesn't exist" when attempting to deploy on testnet

### ISSUE THREAD

**Issue by Jharmony** [hashlips-lab/nft-erc721-collection#290]
### General information
| Description | Value |
| --- | --- |
| Project version | 2.3.0 |
| Operating system and version | Windows 11 64-bit OS  |
| NodeJS version | 16.15.0 |
| NPM version | 8.5.5 |
| Yarn version | 1.22.19 |
| Truffle version |0.0.0 |

### Describe the bug
After installing all the necessary dependencies on the nft-erc721-collection app an error keeps appearing when I attempt to deploy the contract on the rinkeby testnet. All of the appropriate api keys have been entered into the .env file as well.

### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):
1. Go to '/smart-contract/ folder and run yarn deploy --network rinkeby   '
2. This error appears after running the deploy command Error HH100: Network rinkeby doesn't exist

### Expected behavior
I expected the contract to be successfully deployed onto the rinkeby testnet after verifying details to be correct in the .env file

### Screenshots
![Untitled-1](https://user-images.githubusercontent.com/22645740/169685260-3a831ab1-a5ec-4def-b6db-cf6e9ba47c12.png)

**Comment by StarSailerDev** [comment]
try yarn deploy --network testnet

**Comment by liarco** [comment]
Thanks @StarSailerDev for your contribution. The answer was actually correct. The network name changed between v1 and v2 in order to support multiple chains with the same commands for `mainnet` and `testnet`.
