### ISSUE TITLE
Cannot install truffle

### ISSUE THREAD

**Issue by Catzskull** [hashlips-lab/nft-erc721-collection#291]
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/truffle
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/truffle'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/truffle'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/truffle'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathanseverin/.npm/_logs/2022-05-23T18_29_18_834Z-debug-0.log
jonathanseverin@iMac nft-erc721-collection-2.3.0 %

**Comment by zeroesiel** [comment]
Same problem here

**Comment by liarco** [comment]
Hi @Catzskull and @zeroesiel,
Support request should be opened in the Discussions section, issues are for bug reports only. Truffle Dashboard is an external tool so we can't provide direct support for it, but you can find my video tutorials on how to install all the dependencies on any operating system: https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials

If you are still struggling with that, then you may have some uncommon configuration on your computer so I would suggest asking the Truffle team for support: https://github.com/trufflesuite/truffle/issues

I hope this helps.
