### ISSUE TITLE
Convert old syntax class components to functional components 

### ISSUE THREAD

**Issue by AlfieDarko** [hashlips-lab/nft-erc721-collection#3]
Great library by the way, appreciate the work you all have put in!

Is there a specific reason you went with the old react syntax? If not, I may have a crack at updating it to the newer functional component based syntax!

**Comment by liarco** [comment]
Hi @AlfieDarko, thank you for your feedback.

To be honest with you, I think the main reason is simply one: I'm used to it.
I know this may not sound a good reason, but structuring the code that way helped me a lot having a clear picture of how I was dealing with the app state and also dealing with TypeScript.

Would you mind sharing some thoughts and examples about this topic so I can think about it?

I don't know how much this might be a breaking change, we may have to wait for a next major release to switch to it, but I have nothing against it if it can bring improvements to the project. 😉

**Comment by ffakenz** [comment]
does it make sense to use redux?

**Comment by liarco** [comment]
> does it make sense to use redux?

Hi @ffakenz, it might be a good idea... any option can be taken into consideration, but we must keep in mind that this DAPP is just meant for quick and effective token sale.

The main goal is (and will always be) to find the best compromise between UX and DX while also keeping a lightweight codebase for easier maintenance. 😉

**Comment by Patrizi5** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/97971328/157976986-e8cf57d6-2542-475e-b11b-8e39e478174b.png)

**Comment by Patrizi5** [comment]
not sure why this is happening, need help

**Comment by liarco** [comment]
I'm closing this since I don't have enough experience with the other paradigm (and also time) to convert and maintain the new implementation on my own. We might return to this in the future, but at the moment there is no plan to change this.

Thank you everyone for the feedback.
