### ISSUE TITLE
Updating already deployed contract

### ISSUE THREAD

**Issue by mpixelz** [hashlips-lab/nft-erc721-collection#318]
Hi,
We have already deployed a contract and have gone thru the whitelisted, pre-sale, reveal and public mint functions.. 
but as the market is in downtrend we would like to update the price of pre-sale and public mint.
so we can have a lower pre-sale and still get the option to update the price higher on public mint. i see we have an option to update the public mint price on etherscan contract but is there a way to update both thru the contract?
we're using v1 of the tool here.
Please let me know if that is possible.
Thanks.

**Comment by liarco** [comment]
Hi @mpixelz, please follow the instructions when opening issues. Issues must be used for bug reports only, community support or questions should be asked in the [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions). Also, any bug report must include all the required information or the issue will be marked as invalid.

Thanks for your understanding.
