### ISSUE TITLE
Cant install Node_Modules in Smart-Contract

### ISSUE THREAD

**Issue by ClubPEC** [hashlips-lab/nft-erc721-collection#32]
Dear Hashlips and Marco

I would like to thank you two for an amazing work. 

Having issues while using new 5 min method to deploy 

yarn install v1.22.15
warning package.json: No license field
warning @hashlips-lab/nft-erc721-collection-smart-contract@1.0.1: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

However Node_Module gets installed in nft-erc721-collection when run Yarn.
Also, when try to change the name - yarn rename-contract NEW_CONTRACT_NAME below error 
yarn run v1.22.15
warning package.json: No license field
$ hardhat rename-contract pec
'hardhat' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Your help appreciated 
Thanks 
PEC

**Comment by liarco** [comment]
Hi @ClubPEC, did you try searching for `error Couldn't find the binary git` from the issues panel? I think #5 might help you.

Feel free to let me know here if you are still having issues with this.

**Comment by liarco** [comment]
Also, please make sure you are running `yarn` on both `/smart-contract` and `minting-dapp` because the second error make me thing that you don't have your dependency installed properly there.

**Comment by ClubPEC** [comment]
> Hi @ClubPEC, did you try searching for `error Couldn't find the binary git` from the issues panel? I think #5 might help you.
> 
> Feel free to let me know here if you are still having issues with this.

In Hashlips word "Worked as a Charm" . Thank you so much Marco :))
