### ISSUE TITLE
ERC721AQueryable "TypeError: Function needs to specify overridden contracts "ERC721A" and "IERC72A"

### ISSUE THREAD

**Issue by btroia** [hashlips-lab/nft-erc721-collection#321]
Hi! I am trying to compile the example `ERC721AQueryable` contract (bot via the VSCode Ethereum Remix plugin and web-based Remix) but seeing the following error:

VSCode:
<img width="500" alt="Screen Shot1" src="https://user-images.githubusercontent.com/368747/172941715-d238331b-d20c-41d5-8af3-91bf3df53fa6.png">

Remix:
<img width="600" alt="Screen Shot" src="https://user-images.githubusercontent.com/368747/172941493-2ceac342-8c23-4085-bec7-9a1aeab2a6dd.png">

I am importing the following:

```javascript
import "erc721a/contracts/extensions/ERC721AQueryable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Strings.sol";

contract MyNftToken is ERC721AQueryable, Ownable, ReentrancyGuard {
```

Thanks in advance for any help/direction!

**Comment by liarco** [comment]
Duplicate of #312
