### ISSUE TITLE
Blank HTML Page when Building Minting DAPP

### ISSUE THREAD

**Issue by ZCBERY** [hashlips-lab/nft-erc721-collection#33]
Hi! This whole tutorial has been a breeze and I have gotten stuck right at the end. After building the minting dapp and trying to open the HTML file the only thing I am left with is a blank page with a broken image and the text "logo". If anyone has the solution for this problem it would be greatly appreciated!

**Comment by liarco** [comment]
Hi @ZCBERY, the DAPP is supposed to be deployed on the root path of your domain.
From your description is seems like you are trying deploying it inside a subfolder (e.g. `https://www.example.com/mint` would not work, I suggest creating a dedicated subdomain such as `https://mint.example.com`)

**Comment by liarco** [comment]
I guess it worked... 😅
