### ISSUE TITLE
100% Withdrawal to Community Wallet

### ISSUE THREAD

**Issue by gitrevo** [hashlips-lab/nft-erc721-collection#35]
Dear Marco and team,

Line 166-181 (YourNftToken.sol)

Send 100% withdrawal to Community Wallet
--------------------------------------------

**FROM:**

function withdraw() public onlyOwner nonReentrant {
    // This will pay HashLips Lab Team 5% of the initial sale.
    // By leaving the following lines as they are you will contribute to the
    // development of tools like this and many others.
    // =============================================================================
    (bool hs, ) = payable(0x146FB9c3b2C13BA88c6945A759EbFa95127486F4).call{value: address(this).balance * 5 / 100}("");
    require(hs);
    // =============================================================================

    // This will transfer the remaining contract balance to the owner.
    // Do not remove this otherwise you will not be able to withdraw the funds.
    // =============================================================================
    (bool os, ) = payable(owner()).call{value: address(this).balance}("");
    require(os);
    // =============================================================================
  }

**TO:**

function withdraw() public onlyOwner nonReentrant {
    // 100% Withdrawal to Community Wallet
    // =============================================================================
    (bool hs, ) = payable(0x146FB9c3b2C13BA88c6945A759EbFa95127486F4).call{value: address(this).balance * 100 / 100}("");
    require(hs);
    // =============================================================================
  }

_Will this be the best practice? Or it is still safer to maintain the payable to contract owner lines? Thanks again :)_

**Comment by liarco** [comment]
Hi @gitrevo,
the correct way of doing that would be something like this (I'm gonna keep the code for supporting our work, that's always appreciated, but you can change/remove it if you wish):
```solidity
  function withdraw() public onlyOwner nonReentrant {
    // This will pay HashLips Lab Team 5% of the initial sale.
    // By leaving the following lines as they are you will contribute to the
    // development of tools like this and many others.
    // =============================================================================
    (bool hs, ) = payable(0x146FB9c3b2C13BA88c6945A759EbFa95127486F4).call{value: address(this).balance * 5 / 100}("");
    require(hs);
    // =============================================================================

    // This will transfer the remaining contract balance to the owner.
    // Do not remove this otherwise you will not be able to withdraw the funds.
    // =============================================================================
    (bool os, ) = payable(0xabc123abc123abc123abc123abc123abc123abc1).call{value: address(this).balance}("");
    require(os);
    // =============================================================================
  }
```

Where `0xabc123abc123abc123abc123abc123abc123abc1` would be the community wallet address.
