### ISSUE TITLE
when I open http://127.0.0.1:8080/ for the minting dapp, and I try to connect my metamask wallet(i'm in the rinkeby network and also truffle is running-followed the tutorial) , but it says Error-unsupported network , I have followed the tutorial , what do  I have to do ?

### ISSUE THREAD

**Issue by thenewdev2022** [hashlips-lab/nft-erc721-collection#367]
### General information
| Description | Value |
| --- | --- |
| Project version | X.Y.Z |
| Operating system and version | ??? |
| NodeJS version | X.Y.Z |
| NPM version | X.Y.Z |
| Yarn version | X.Y.Z |
| Truffle version | X.Y.Z |

### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):

**Comment by thenewdev2022** [comment]
![image](https://user-images.githubusercontent.com/110031112/180992476-91a61446-ee37-434a-806d-a8c5a2d8b49a.png)

**Comment by svensei** [comment]
![image](https://user-images.githubusercontent.com/38038197/181019646-414d7792-b0d1-4bef-a865-39dc245eb679.png)


const CollectionConfig: CollectionConfigInterface = {
  testnet: Networks.ethereumTestnet,
  mainnet: Networks.ethereumMainnet,

Just change hardhatLocal > ethereumTestnet , that worked for me :)

**Comment by thenewdev2022** [comment]
THANK YOU SOO MUCH MAN .... I appreciate the help ,i was kinda hesitant to ask ,the code works perfectly u actually made my mad . THANKS.

**Comment by svensei** [comment]
No problem my friend, I am glad I could help :) LFBuild

**Comment by liarco** [comment]
Thank you @svensei for taking time to help!
