### ISSUE TITLE
yarn run dev is not working

### ISSUE THREAD

**Issue by bloddycrocodile** [hashlips-lab/nft-erc721-collection#382]
I have a issue
please help
![img (4)](https://user-images.githubusercontent.com/110161438/184548234-d6700a05-9a80-4907-a3e1-c024c08cb34b.png)

**Comment by liarco** [comment]
Hi, please read the rules and search for similar issues before opening a new one.

Duplicate https://github.com/hashlips-lab/nft-erc721-collection/issues/299#issuecomment-1148554547
