### ISSUE TITLE
Tokens on Rarible are not showing after contract deploy

### ISSUE THREAD

**Issue by minhazrafsan** [hashlips-lab/nft-erc721-collection#390]
### Discussed in https://github.com/hashlips-lab/nft-erc721-collection/discussions/210

<div type='discussions-op-text'>

<sup>Originally posted by **ecerroni** April  4, 2022</sup>
There seems to be a recurring issue in getting the tokens being displayed on OpenSea after successfully deploying the contract.

Unfortunately, I've been of those that experienced this before hand. I tried to investigate the issue in many ways as I wanted to check if it was something related to the contract or because of OpenSea.

My conclusions are that **the contract in its current implementation is totally fine**. The issue seems to be with OpenSea and how it handles new contracts deployed on the block chain. 

Generally the issues the user may facing are:
- error messages while trying importing the contract: _"We couldn't find this contract. Please ensure that this is a valid ERC721 or ERC1155 contract deployed on Ethereum/Polygon and that you have already minted items on the contract."_
- Contract has been imported, but none or less tokens are listed

This is mainly on OpenSea side. I found an interesting article that sums it up quite well:

-----------------------
Based on observed behavior this is how OpenSea ERC721 validation works:

1. OpenSea automatically monitors all new contracts that are deployed. The moment OpenSea detects a new contract has been deployed it calls contract.supportsInterface(type(IERC721).interfaceId) on that contract. If the function call returns true then OpenSea adds it to its list or database of potential ERC721 contracts. If the function call returns false then OpenSea will not detect it as an ERC721 contract and any attempts at validation fails.

2. OpenSea checks during deployment and after deployment (for any contract that passes step 1 above) if any ERC721 Transfer events have been emitted from a contract. If not then any validation fails.

If a contract passes step 1 and 2 then it will pass ERC721 validation on

-----------------------

ref: https://dev.to/mudgen/how-to-solve-openseas-we-couldnt-find-this-contract-during-erc721-validation-4lp2

There are many issues that people opened on this repo that claim having these kind of problem. Both Ethereum and Polygon may be affected with Polygon being significantly more vulnerable to this. Personally I deployed on Polygon when I had this issue.

The fact that successfully deploying the contract to testnets first does not prevent this kind of issues on the mainet.

As @liarco himself pointed out there is no rule here, but a single mint operation with thousands of tokens can have negative impact on the expected outcome.

My 0.02 is that:
- OpenSea db update cannot catch up with thousand of events firing at the same time for a single contract, it throws an error and the minting events are gone forever from their point of view
- OpenSea does not like thousands of concurrent mints at the same time in the first place and it just ignore them. Maybe it sees is as spam.
- OpenSea/Blockchain integration is far from perfect and things get lost with this kind of excessive load, especially on Polygon

The above assumptions are based on my personal circumstantial evidence:
1. I deployed the contract
2. I minted 4947 items
3. I cannot import the contract (I tried twice a day)
4. In the meantime contract is imported on Rarible (after 6 days of failed attempts), Refinable (although with the help of their devs) and NFTrade (quite quickly) with all 4947 items showing properly.
5. after 2 weeks I mint an additional item
6. I was able to finally import the contract on OpenSea with one item showing (the last mint only)
7. nothing changed for 3 days
8. I did transfer one of the initial minted items from me to myself again. This item showed up on OpenSea under the collection after just a few minutes.

So the main takeaway is to **not mint all at once**. I am also keen to believe that with the standard process of minting through the dapp will not result in any issue.

Any contribution to this discussion is very welcome.

</div>

**Comment by liarco** [comment]
Hi, thank you for providing so many details about this topic. Anyway, issues are intended for bug report only so I kindly ask you to use #210 for any follow up on this.

Thank you for your understanding.
