### ISSUE TITLE
Minting Dapp showing "Unsupported network!" when deployed on Goerli.

### ISSUE THREAD

**Issue by laurin-kraemer** [hashlips-lab/nft-erc721-collection#399]
Background: For testing purposes, I deployed the smart contract on Goerli which worked fine. 

Problem: I ran into an issue when I tried to spin off the mining dapp as it is saying "Unsupported network!" if I try to connect to Metamask. 

Proposed Solution: I tried changing Networks in 'smart-contract/lib/Networks' from Rinkeby (chainID: 4) to Goerli (chainID: 5) but that didn't fix the problem for me.

**Comment by goodshipdev** [comment]
I am having the same issue. Any solution would be appreciated.

**Comment by Faisal-FS** [comment]
Got the same problem. 
After debugging the minting-dapp react code, I found the solution. 

Just you have to update CollectionConfig file in the smart-contract code. Follow these steps:

1. Goto the file \smart-contract\config\CollectionConfig.ts
2. Check your test network from the \lib\Networks.ts
3. Update CollectionConfig line 7 with the your test network.

Screenshot for better understanding: 
![image](https://user-images.githubusercontent.com/25268271/190144629-7e7bdf8f-7754-4779-916b-07f8e1e0b36e.png)

Thanks

**Comment by jvel07** [comment]
Is Goerli's chain ID 420?

**Comment by laurin-kraemer** [comment]
Thank you @Faisal-FS for the proposed solution. It worked! 

@jvel07 The chain ID for Goerli is 5!

**Comment by liarco** [comment]
Thank you @laurin-kraemer for helping out.

I just released a patch version ([2.4.3](https://github.com/hashlips-lab/nft-erc721-collection/releases/tag/2.4.3)) which moves to Goerli as the official testnet for Ethereum. The patch can be manually applied by simply following the changes in #404.

Hope this is gonna help anyone facing the same issue.
