### ISSUE TITLE
Issues deploying and verifying as a contract

### ISSUE THREAD

**Issue by justinsteu** [hashlips-lab/nft-erc721-collection#4]
When I try to deploy the contract and then verify the contract I get this error.

After I run **yarn deploy --network (network name)** and go to check out the contract on etherscan, It labels my contract as an address and not a contract.
![Screen Shot 2022-02-17 at 5 00 45 PM](https://user-images.githubusercontent.com/97767644/154597415-a96337a1-2200-489f-96b5-e148e70d7402.png)

Then when I try to verify the contract by running **yarn verify (address) --network (network name)** I get this error:

Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://api-rinkeby.etherscan.io/api
Reason: The Etherscan API responded that the address (address) does not have bytecode.

Am I missing something with deploying and verifying?

Thanks.

**Comment by NFTSmart** [comment]
Deploying and verifying works fine just check video makes sure you dont skip any steps, also ethscan can take few hrs to update give it some time

**Comment by justinsteu** [comment]
Thank you for your reply, you were correct, etherscan had not updated yet. This is my first time not deploying the contract via Remix, so I was not used to the wait time. Everything is works amazing, the whitelist works perfect as well as public sale.

**Comment by justinsteu** [comment]
@leofanggithub I did get it to verify, had to wait 2-3hrs before etherscan updated and said that it  was verified.
