### ISSUE TITLE
Verify Contract  on the Goerli test net and fix

### ISSUE THREAD

**Issue by sal-420** [hashlips-lab/nft-erc721-collection#406]
The verify command throws the below error

Error in plugin @nomiclabs/hardhat-etherscan: Please provide an Etherscan API token via hardhat config. For example:

{
  ...
  etherscan: {
    apiKey: {
      goerli: 'your API key'
    }
  }
}

The fix is top update the hardhatconfig.ts file with the gorerli block explorer (goerli: process.env.BLOCK_EXPLORER_API_KEY,) see below

    apiKey: {
      // Ethereum
      rinkeby: process.env.BLOCK_EXPLORER_API_KEY,
      goerli: process.env.BLOCK_EXPLORER_API_KEY,
      mainnet: process.env.BLOCK_EXPLORER_API_KEY,

**Comment by liarco** [comment]
Thank you @sal-420 for your contribution, I deployed the fix and it is gonna be included in the next patch release.
