### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by bolisteward** [hashlips-lab/nft-erc721-collection#409]
### General information
| Description | Value |
| --- | --- |
| Project version | 2.4.4 |
| Operating system and version | windows 11 home |
| NodeJS version | 16.17.0 |
| NPM version | 8.15.0  |
| Yarn version | 1.22.19 |
| Truffle version | 5.5.31 |

I get the next issue when I try to verify the contract
Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key

**Comment by liarco** [comment]
Hi @bolisteward,
which chain are you working on? Please remember that any chain has its own verification API key (e.g. Etherscan API key won't work on Polygon, and so on). If you haven't already, I also highly recommend you to watch my [video tutorials (YouTube)](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials) to get instructions about how to take every single step correctly.

Let me know if this helps.
