### ISSUE TITLE
Running yarn dev-server results in Error TS2345: Argument of type 'Signer | Provider' is not assignable ...

### ISSUE THREAD

**Issue by Zivsun12** [hashlips-lab/nft-erc721-collection#416]
### General information
| Description | Value |
| --- | --- |
| Project version | nft-erc721-collection-2.4.4 |
| Operating system and version |Win 10 Ent, Version 1909 |
| NodeJS version | v16.17.1 |
| NPM version | 8.15.0 |
| Yarn version | v1.22.19 |
| Truffle version | v5.6.1 |

### Describe the bug
Running yarn dev-server results in Error the following
ERROR in C:\Users\Zivsun\Desktop\NFT\Source\nft-erc721-collection-2.4.4\smart-contract\typechain\factories\Ownable__factory.ts(73,40)    
      TS2345: Argument of type 'Signer | Provider' is not assignable to parameter of type 'Provider | Signer | undefined'.
  Type 'Provider' is not assignable to type 'Provider | Signer | undefined'.

### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):

**Comment by liarco** [comment]
Hi @Zivsun12,
I tried reproducing this error with the following commands on my machine:
```bash
$ git clone git@github.com:hashlips-lab/nft-erc721-collection.git
...
$ cd nft-erc721-collection/smart-contract/
$ yarn
...
$ yarn compile
...
$ cd ../minting-dapp/
$ yarn
...
$ yarn dev-server
...
```

And everything works fine. Did you make any manual changes to the code? Maybe you forgot to compile again after you renamed the contract, I know this is a common mistake.

Please try deleting your cache files inside the hardhat folder and then compile again, cache can be found in the following paths:
* `../smart-contract/artifacts`
* `../smart-contract/cache`
* `../smart-contract/typechain`

**Comment by Zivsun12** [comment]
Thanks @liarco , might seem as a stupid question as I am new at this, do you mean delete above mentioned folders

**Comment by liarco** [comment]
@Zivsun12 no worries, there is no such thing as "stupid questions", everyone started from zero here.

Anyway, yes, you can delete those folders. Hardhat recreates them when needed. Don't forget to run `yarn compile` from inside `./smart-contract` again before running the dev-server because this is required for the Dapp to work properly.

**Comment by Zivsun12** [comment]
@liarco , you are a STAR, it did not work at first, so I ended up downloading a fresh copy of the repo.
Work perfectly.
Got to say your videos' are amazing

**Comment by accountKarim** [comment]
Hello, I have the same problem, can't find the solution?
