### ISSUE TITLE
Cannot connect to the network truffle

### ISSUE THREAD

**Issue by nbnb666666** [hashlips-lab/nft-erc721-collection#422]
### General information
| Description: While I was following the No6 youtube video about truffle. I tried to yarn deploy --network truffle. I get an error message all the time
| Project version: 2.44
| Operating system and version | win10
| Yarn version | 1.22.19
| Truffle version | X.Y.Z |

### Describe the bug
While I was following the No6 youtube video about truffle. I tried to yarn deploy --network truffle. I get an error 

### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):
1. entering yarn deploy --network truffle

### Screenshots
![ff1bdc93618dac4f1d150a8be20b310](https://user-images.githubusercontent.com/83274037/198823712-b1889bc2-affc-4381-a8ea-cc84794eb649.jpg)

**Comment by sal-420** [comment]
did you first start truffle with command: `truffle dashboard`

**Comment by nbnb666666** [comment]
> 

Yep, the truffle dashboard works fine, I can connect to my wallet. But once I try to deploy my contract the error comes up.

**Comment by Iffat77** [comment]
Hello, Im running into this exact issue and was wondering if a solution was found?
