### ISSUE TITLE
error Couldn't find the binary git

### ISSUE THREAD

**Issue by PhrygianX** [hashlips-lab/nft-erc721-collection#424]
Hello guys
I tried to run this cmd but it doesn't work

PS C:\Users\DELL\Desktop\nft-erc721-collection-2.4.4> cd smart-contract
PS C:\Users\DELL\Desktop\nft-erc721-collection-2.4.4\smart-contract> yarn
yarn install v1.22.19
warning ..\..\..\package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by sal-420** [comment]
try installing yarn from vs code terminal instead the power shell terminal

**Comment by liarco** [comment]
Hi @PhrygianX, issues must follow the provided template and include all the requested information. Also please use the search tool before opening a new issue: https://github.com/hashlips-lab/nft-erc721-collection/issues?q=is%3Aissue+binary+git

Thanks
