### ISSUE TITLE
Cannot connect to network Truffle

### ISSUE THREAD

**Issue by Iffat77** [hashlips-lab/nft-erc721-collection#425]
General information
| Project version: 2.4.4
| Operating system and version |  MacOS monterey 12.3.1
| Yarn version | 1.22.19
| Truffle v5.6.7 (core: 5.6.7)
Ganache v7.5.0
Solidity v0.5.16 (solc-js)
Node v16.14.2
Web3.js v1.7.4

Describe the bug
I enter truffle dashboard to get an instance of the dashboard running and connect my wallet on the goerli testnet 
After that I enter yarn deploy --network truffle and get the error "HardhatError: HH108: Cannot connect to the network truffle.
![Screen Shot 2022-11-27 at 9 47 49 PM](https://user-images.githubusercontent.com/95243164/204181230-9b8d807f-f2c7-4647-a49c-0674dee70b46.png)
![Screen Shot 2022-11-27 at 9 48 21 PM](https://user-images.githubusercontent.com/95243164/204181231-19fde89d-1972-4961-9d61-e692eae9a651.png)
![Screen Shot 2022-11-27 at 9 49 04 PM](https://user-images.githubusercontent.com/95243164/204181233-90e0d28d-99a4-437d-9ef5-ff4f73f57162.png)
![Screen Shot 2022-11-27 at 9 49 12 PM](https://user-images.githubusercontent.com/95243164/204181234-d3f94504-e7db-4d76-83fd-fdee2c6cf16e.png)
"

How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):

entering yarn deploy --network truffle

**Comment by liarco** [comment]
Hi @Iffat77, thank you for reporting this. Will take a look at it ASAP.

**Comment by liarco** [comment]
Hi @Iffat77, thank you for

**Comment by Iffat77** [comment]
Hello @liarco, It seems to be working now and I haven't changed anything, I think Ill have to put the error to the testnet itself maybe. Thank you for your time.
