### ISSUE TITLE
Adding Opensea storefront-level metadata for your contract

### ISSUE THREAD

**Issue by absnft** [hashlips-lab/nft-erc721-collection#43]
Hi Liarco

Can you please help with adding opensea storefront-level metadata for your contract(https://docs.opensea.io/docs/contract-level-metadata) in the contract, to set royalties & have storefront metadata filter for the collection.

I'm currently using the ERC721A within Hashlips-lab's nft-erc-721-collection repo.

**Comment by liarco** [comment]
Hi @absnft, this topic has been already discussed in #12 and #20.

> I'm currently using the ERC721A within Hashlips-lab's nft-erc-721-collection repo.

`ERC721A` contract is not officially supported here, we are working on an official integration to be merged asap (#29) but it's still not ready for production usage.
