### ISSUE TITLE
How to have initial mints to owner?

### ISSUE THREAD

**Issue by JohnCarp** [hashlips-lab/nft-erc721-collection#447]
Hey @liarco! 

So I'm not sure this is a bug or not but one of the comments mentioned this was not working? 

https://github.com/hashlips-lab/nft-erc721-collection/issues/39#issuecomment-1153163518

I seen you left this comment previously to that:

https://github.com/hashlips-lab/nft-erc721-collection/issues/39#issuecomment-1064064456

Essentially I would like to mint a certain amount like 100 to keep for the team. A couple questions on this:

* Is this code working or is there really a bug?
* Does this happen when the contract is deployed?
* If not does it happen when we make the mint live?

Thank you for the help and apologies if this was not a bug!

**Comment by mewmix** [comment]
This constructor minted 100 nfts on my testing , per the author's referenced comments. Would advise to test on your own for further safety.


```solidity
  constructor(
    string memory _tokenName,
    string memory _tokenSymbol,
    uint256 _cost,
    uint256 _maxSupply,
    uint256 _maxMintAmountPerTx,
    string memory _hiddenMetadataUri
  ) ERC721A(_tokenName, _tokenSymbol) {
    setCost(_cost);
    maxSupply = _maxSupply;
    setMaxMintAmountPerTx(_maxMintAmountPerTx);
    setHiddenMetadataUri(_hiddenMetadataUri);
    _safeMint(msg.sender, 100);

  }
```

**Comment by liarco** [comment]
Thank you very much @mewmix for you help. I have to move this to discussions since it's not really a bug report.
