### ISSUE TITLE
Module build failed: Module not found:

### ISSUE THREAD

**Issue by NishantPacharne** [hashlips-lab/nft-erc721-collection#451]
project version: 2.4.5

### Describe the bug
I'm getting this error "Module build failed: Module not found"  
"./src/scripts/react/Dapp.tsx" contains a reference to the file "../../../../smart-contract/artifacts/contracts".

### How to Reproduce
I'm trying to deploy this on vercel and I get this error.

### Expected behavior
It was expected that the build shall work fine.

**Comment by liarco** [comment]
Hi @NishantPacharne,
thank you for reaching out, but this is not a bug: you are not deploying the dapp correctly. I highly recommend checking out my video series about how to use this tool (you can find the links to each episode in the [README file](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials)). The deployment tutorial is about CloudFlare, but you should be able to apply the same configuration to Vercel as well.

Please note that we provide support to [Open Devs Crew](https://opendevs.io/) holders, feel free to join if you find our work useful. :)
