### ISSUE TITLE
Can't rename "rename-contract" file

### ISSUE THREAD

**Issue by Abubakr22** [hashlips-lab/nft-erc721-collection#461]
PS C:\Users\sarda\Downloads\NFT erc721> yarn rename-contract Wild_Shells
yarn run v1.22.19
error Command "rename-contract" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\sarda\Downloads\NFT erc721>

**Comment by liarco** [comment]
Hi @Abubakr22,
I'm sorry but this issue appears to be invalid as you are not providing the required information. Issues are open for bug reports only so I need you to send information about your setup and the exact steps to reproduce the error.

Looking at just this I think you are probably in the wrong folder, this error is impossible to reproduce with a properly configured machine/project. If you need help with using our tools I provide this kind of support to holders of ODC holders only (https://opendevs.io), this helps me focusing my limited time to people who are actively supporting my work. Feel free to join our private channel on Discord to ask for questions about custom implementations or get early access to new tools.

Have a great day!
