### ISSUE TITLE
Adding new styles to dapp (TailwindCss)

### ISSUE THREAD

**Issue by juanantonionunez** [hashlips-lab/nft-erc721-collection#47]
Hi Liarco, I need to adapt my website to the Hashlips minting dapp but I don't know if this question is appropriate because I'm very new to TailWindCss and when I try to add certain new css styles to the ones already created I'm getting compilation errors. How can I recompile the css to create new styles and be able to use them in the dapp? Thank you

**Comment by liarco** [comment]
Hi @juanantonionunez,
The project is using SCSS and Tailwind, but you should be able to put plain CSS in any `*.scss` file and it should work properly. Can you please share some examples of code you changed that gives you errors?

**Comment by juanantonionunez** [comment]
Hi @liarco, errors happens when i try to add some tailwind style wich is not included, as a new color, etc...
For example, if i want to do @apply bg-primary-500; preprocessor will fail

**Comment by juanantonionunez** [comment]
@liarco for example if you create a new class of a button without background, outlined, and with a new color you're able to do it? Glad if i can see that.

Thanks

**Comment by liarco** [comment]
Absolutely @juanantonionunez, here is an example I hope this helps...

### Final result
<img width="785" alt="Screen Shot 2022-03-01 at 17 19 00" src="https://user-images.githubusercontent.com/1532277/156206771-7f324dec-8c53-4226-84dc-51fd3219465a.png">

### Source code
```ts
// minting-dapp/tailwind.config.js
// ...
        colors: {
            popupsbg: colors.white,
            neutral: colors.slate,
            primary: colors.indigo,
            primarytxt: colors.white,
            warning: colors.yellow,
            warningtxt: colors.black,
            error: colors.red,
            errortxt: colors.white,
            'custom-gh': colors.lime, // <--- here I add a custom color matching "lime" from the Tailwind CSS docs
        }
// ...
```

```scss
// minting-dapp/src/styles/components/general.scss
// ...
button.extra {
  @apply bg-none;
  @apply border-2 border-error-600;
  @apply hover:bg-custom-gh-500;
}
// ...
```

```tsx
// minting-dapp/src/scripts/react/Dapp.tsx
// ...
            <button className="extra">Test for GitHub</button>
// ...
```

Let me know if you need anything else 😉

**Comment by tab00** [comment]
Doesn't scss make the code more complicated unnecessarily?

From https://tailwindcss.com/docs/using-with-preprocessors :
> you don’t need to use a preprocessor with Tailwind — you typically write very little CSS on a Tailwind project anyways so using a preprocessor just isn’t as beneficial as it would be in a project where you write a lot of custom CSS.

How can we integrate third party Tailwind template code e.g. https://github.com/Landish/react-tailwindcss-demo ?

**Comment by liarco** [comment]
Hi @tab00,
Thank you for your feedback, I find it a bit confusing to have so many classes polluting the markup, that's why I usually try to achieve a full separation between markup and styles. I know this might sound old-school, but I need to be able to customize the DAPP quickly and this approach makes it easier to do so.

Of course with minimum tweaks in the config (if really needed) you can change Tailwind's behavior as you wish and you can also remove the whole SCSS code and start with a completely custom design and a clean markup boilerplate.

Here are some pros and cons that I find...

### Pros
- markup and styles separation (higher customization without changing too much)
- cleaner markup code (better semantic use of tags and improved readability)
- possibility to start designing from scratch in no-time (simply deleting the SCSS code)
- possibility for unexperienced users to make minor tweaks easily (even using plain CSS)

### Cons
- uncommon use of Tailwind
- unfamiliar `@apply` syntax

**Comment by monsterhive123** [comment]
@liarco Do u think you'll be doing a tutorial soon on how to customize the minting dapp? As that would be really helpful for us.

**Comment by monsterhive123** [comment]
@liarco could you expand on this please "possibility for unexperienced users to make minor tweaks easily (even using plain CSS)." As I'm quite new to programming in general I don't really understand scss how do we replace scss with CSS thank you.

**Comment by tab00** [comment]
Thanks @liarco for the explanation.

Though a problem I had encountered is that different HTML text tags all appear the same when intuitively we expect them to appear differently. e.g. header text appears exactly like p text.

This HTML 
```
  <main>
    <img id="logo" src="/build/images/logo.png" alt="Logo" />

    <h1>My NFT collection</h1>
    <h2>subheading</h2>
    <p>p text.</p>
```
appears as:

![image](https://user-images.githubusercontent.com/12715448/156297121-1856734a-4f11-4b62-bf83-122b3ee7327b.png)


If we want to import a professional third party Tailwind template what would we need to do?

**Comment by tab00** [comment]
What'd be the best alternative style framework to just get things looking good fast? I've used Bootstrap since version 3, but it can get messy when customizing, and now there are so many others to choose from.

**Comment by BobbyBorisov** [comment]
@liarco you are the real MVP, this workshop will be definitely helpful for everybody
