### ISSUE TITLE
I try to upload the site with heroku - get path errors for some files  like whitelist.json  CollectionConfig ...

### ISSUE THREAD

**Issue by GalinaKaz** [hashlips-lab/nft-erc721-collection#51]
ERROR  Failed to compile with 3 errors12:00:05 PM
remote:
remote:        Module build failed: Module not found:
remote: <s> [webpack.Progress] 99% done plugins
remote: <s> [webpack.Progress] 99%
remote:
remote:        "./src/scripts/lib/Whitelist.ts" contains a reference to the file "../../../../smart-contract/config/whitelist.json".
remote: <s> [webpack.Progress] 99% cache begin idle
remote: <s> [webpack.Progress] 99% cache begin idle
remote:        This file can not be found, please check it for typos or update it if the file got moved.
remote: <s> [webpack.Progress] 100%
remote:
remote:
remote: <s> [webpack.Progress] 99% cache shutdown
remote: <s> [webpack.Progress] 99% cache shutdown
remote:        "./src/scripts/react/Dapp.tsx" contains a reference to the file "../../../../smart-contract/config/CollectionConfig".
remote: <s> [webpack.Progress] 100%
remote:
remote:        This file can not be found, please check it for typos or update it if the file got moved.
remote:
remote:        "./src/scripts/react/Dapp.tsx" contains a reference to the file "../../../../smart-contract/artifacts/contracts".
remote:        This file can not be found, please check it for typos or update it if the file got moved.
remote:
remote:        Entrypoint main = main.css main.js
remote:        Entrypoint _tmp_copy = 3 auxiliary assets
remote:        webpack compiled with 8 errors
remote: error Command failed with exit code 1.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to seahorse-erc721-minting-dapp.
remote:
To https://git.heroku.com/seahorse-erc721-minting-dapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/seahorse-erc721-minting-dapp.git'
PS D:\ART LIFE Freelancer LIFE\crypto\HASHLIPS-NFT CREATE\nft-erc721-collection-1.0.1\minting-dapp>

**Comment by liarco** [comment]
@GalinaKaz sorry but I can't understand the given error.

You should simply build the DAPP from your computer using `yarn build` inside the `/minting-dapp` folder. This command is going to output a static, ready-to-deploy, set of files inside `/minting-dapp/public`. You can take those files and deploy them on any static hosting service.

**Comment by ClubPEC** [comment]
Dear Marco

Hope you are well.

I am too getting similar error after yarn build. HTML do not open. 

Please see attached.
  

Thanks
[HTML error.docx](https://github.com/hashlips-lab/nft-erc721-collection/files/8176804/HTML.error.docx)

**Comment by liarco** [comment]
@ClubPEC you error has nothing to do with Heroku, please open a dedicated issue and also avoid attaching MS Word files, you can attach images directly.

**Comment by GalinaKaz** [comment]
@liarco I success to do the build properly at /minting-dapp  - the public directory created ok .
the issue is when I fry to push from /minting-dapp to HEROKU . then as far as I understand the public directory not used and heroku service is trying to make the build itselt ->  in this stage the failure happens .
if you say it's a problem only with the Heroku service - then fine .  I wouldn't use the heroku service .
I'm trying in parellel create static site on other platform .

**Comment by cavacas** [comment]
While not exactly related, there is an issue with the assumptions that encore is making regarding the webapp not being at the root "/". The way the /build directory is structured is making it really difficult (more than it should) to have this app hosted in a sub directory i.e. domain.com/minting-dapp/ since the /build/ path is absolute. I'm trying to work around it as I need this to be on a sub directory, and if helpful might post back a PR.

**Comment by liarco** [comment]
Hi @cavacas,
it's not actually encore's fault here, it's Webpack that makes all paths absolute by default. I spent a lot of time trying to make it work with relative paths but while it might seem pretty easy, it fails badly with references inside the SCSS code.
A positive side-effect of this is that deploying the minting DAPP to it's own subdomain makes it really easy to manage the main websites independently (and also applying proper anti-DDOS measures).

**Comment by FrancoGedor** [comment]
@cavacas let me know if you find any work around. Having to deploy manually is such a pain specially if you're used to working with Heroku and similar services.

**Comment by FrancoGedor** [comment]
> @GalinaKaz I don't use Heroku for my projects so unfortunately I'm not able to help with this specific issue at the moment, what I would suggest you is copying the content of your `public` folder to another blank repo and then try deploying it to Heroku as a static website with no build involved.
> 
> By the way, I'm gonna host a free workshop next week where I'm gonna show how to do everything with this project (including free deployment of the DAPP). I'm gonna make an announcement soon (between today and tomorrow) on [my YouTube channel](http://www.youtube.com/channel/UCsNUSP49XDIhxaZoZlLwnyw) so subscribe and stay tuned if you are interested in that. ;)

That'd be awesome. Thanks for all your work.

**Comment by Solonnikov** [comment]
> While not exactly related, there is an issue with the assumptions that encore is making regarding the webapp not being at the root "/". The way the /build directory is structured is making it really difficult (more than it should) to have this app hosted in a sub directory i.e. domain.com/minting-dapp/ since the /build/ path is absolute. I'm trying to work around it as I need this to be on a sub directory, and if helpful might post back a PR.

Have you found any solution?

**Comment by cavacas** [comment]
Not really, but i just ended up creating a directory at the same level as the existing build directory, then directed the build output to be ./my-directory/build and changed the index.html paths to be ./build instead of /build. To use you will then just need to go to http://localhost:8080/my-directory instead of / . Then to host it, just upload my-directory to your web server and it will be served out of my-webserver.com/my-directory/

**Comment by slavakurilyak** [comment]
Consider using Github Actions to streamline deployments on Vercel, Netlify, and/or Heroku.

Here are the build steps for Netlify:

<img width="928" alt="netlify" src="https://user-images.githubusercontent.com/6625584/163178701-63c42dcc-5896-44f4-8091-938afa0fddd3.png">

Here are the build & development settings for Vercel:

<img width="764" alt="vercel" src="https://user-images.githubusercontent.com/6625584/163178708-0cdf1ad3-3b32-45c5-a758-46db060d465e.png">

Note, Heroku build process requires additional customization using a [buildpack](https://devcenter.heroku.com/articles/buildpack-api).

Related: Issue #77

**Comment by liarco** [comment]
Thank you @slavakurilyak, awesome job! Since the recent updates in this repo, there is now a shortcut on the root folder for this. Now we also have an official video about deployment: https://youtu.be/uUrbIXUgVz4
