### ISSUE TITLE
Mint button altered 

### ISSUE THREAD

**Issue by monsterhive123** [hashlips-lab/nft-erc721-collection#53]
Hi @liarco, for some reason when I'm trying to change the font, add text colours, or make the text bold it changes my preview image - & + symbols shifting them to the ends of the preview but also changes my mint button size. How do I fix this? Thank you 

![image](https://user-images.githubusercontent.com/96693503/156188308-d41a1ccd-9def-43b4-b0d4-728372fc68b6.png)
![image](https://user-images.githubusercontent.com/96693503/156188432-43a74a58-7bab-4fb0-b5ff-cf62edba96b9.png)

**Comment by liarco** [comment]
Hi @monsterhive123, this is a React app. You can find the markup code in this folder: https://github.com/hashlips-lab/nft-erc721-collection/tree/main/minting-dapp/src/scripts/react
It also uses Tailwind but not from the markup, it's used through the `@apply` keyword in SCSS, check out the code in: https://github.com/hashlips-lab/nft-erc721-collection/tree/main/minting-dapp/src/styles/components

Changes inside the `index.html` file won't have any effect.
