### ISSUE TITLE
`yarn proof` (hardhat generate-proof) does not work for all whitelisted addresses

### ISSUE THREAD

**Issue by ffakenz** [hashlips-lab/nft-erc721-collection#54]
The task `yarn proof` does not return the same results for each whitelisted address compared to its UI counterpart.

Attached images reflect the issue.
![image](https://user-images.githubusercontent.com/14299604/156179320-346595ec-41a4-4633-b094-960f27c4660d.png)
![image](https://user-images.githubusercontent.com/14299604/156182716-c8cddf4e-beb2-4716-93d2-ecd8b27412bd.png)

As u can see, address 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 gives different outputs: 
- succeeds on front-end
- fails on yarn script

**Comment by liarco** [comment]
Hi @ffakenz,
I just tried reproducing this issue:
1. clone repo in brand new folder
2. install dependencies in both folders (`yarn`)
3. compile the contract (`yarn compile`)
4. run the dev server (`yarn dev-server`)
5. generate proof for address `0x70997970C51812dc3A010C7d01b50e0d17dc79C8` from my browser
6. generate proof from CLI (`yarn proof 0x70997970C51812dc3A010C7d01b50e0d17dc79C8`)

**Proof from the browser:**
`0x1ea67ece8df08afb883f510b5ea0a6adf2c9162b8466e8d61a8878bb88c34d87,0xa22d2d4af6076ff70babd4ffc5035bdce39be98f440f86a0ddc202e3cd935a59,0x738cd8ff80600009d71b3733ead051c90641c40206e90292a4ee42eea81fcbdc,0x3679fa6d4868372d580067d8057a9998f0831004796cb0d92889597d256c7b2d,0xc8f97285ebaf38205a5df6d226795bd8f103df91830d9b9e1c08764777f7d019`

**Output from CLI:**
```bash
> yarn proof 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 
yarn run v1.22.10
warning package.json: No license field
$ hardhat generate-proof 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
The whitelist proof for the given address is: 0x1ea67ece8df08afb883f510b5ea0a6adf2c9162b8466e8d61a8878bb88c34d87,0xa22d2d4af6076ff70babd4ffc5035bdce39be98f440f86a0ddc202e3cd935a59,0x738cd8ff80600009d71b3733ead051c90641c40206e90292a4ee42eea81fcbdc,0x3679fa6d4868372d580067d8057a9998f0831004796cb0d92889597d256c7b2d,0xc8f97285ebaf38205a5df6d226795bd8f103df91830d9b9e1c08764777f7d019
✨  Done in 4.57s.
```

They are exactly the same. Remember that if you change the `whitelist.json` file, the CLI will return a value based on the updated list, while the DAPP might need to be rebuilt.

Please try rebuilding your DAPP and let me know if anything changes. 😉

**Comment by ffakenz** [comment]
@liarco 

Thank you so much for your response!

I have just tried the above and still my yarn task keeps failing.
Let me share my console outputs.

![image](https://user-images.githubusercontent.com/14299604/156264497-1dfb4a8b-e303-4ffd-be12-a60e383bddbd.png)
![image](https://user-images.githubusercontent.com/14299604/156264546-a61c8182-4344-4fd0-8119-7775773dcab9.png)
![image](https://user-images.githubusercontent.com/14299604/156264557-17d2f86a-1213-41e9-82fd-ccd15e7ce4fa.png)

What do u think might be the issue ?

Im using yarn version 1.22.17
I doubt yarn is the issue.

Looking forward to your comments!

**Comment by ffakenz** [comment]
@liarco 

thank you so much for your help and response.
indeed its working !

let me explain what was the issue:
if u check in my images, the address is wrong, is like a typo. 
for some reason, when i copy from vscode and paste into iterm the address is missing zeros:
- in whitelist.json file:
0x70997970C51812dc3A010C7d01b50e0d17dc79C8
- when i paste into iterm:
0x7099797C51812dc3A01C7d01b50e0d17dc79C8
as u can see lengths are different.
i dont know why is this happening but its a problem from my side.

i apologize for opening an invalid issue.
once again appriciate the support!
