### ISSUE TITLE
Owner use ‘mint’ or ‘mintForAddress’

### ISSUE THREAD

**Issue by gitrevo** [hashlips-lab/nft-erc721-collection#59]
> > Any chance that you review this Marco? Sometime owner would like to mint for the team say 100 NFTs, tested with 3 nfts and it cost 0.2 gas fee. Imagine if it’s 100 :(
> 
> Please take a look at #50, it might help.

Do you mean, in order for an “owner” to mint without a cost; we need to use “mintForAddress” instead of “mint” right?

i.e:
mintAmount = 200 (200 pcs NFTs)
Address = Owner Wallet Address

![74C5D3BD-FE16-4706-A2D6-B6E6CD9AA1C2](https://user-images.githubusercontent.com/100083426/156712012-c94f65c1-77f8-47ab-9cf8-cfbd69054d4d.jpeg)

Since “mint” will produce error “likely to fail” and huge gas, we need to use “mintForAddress” in order to achieve this correct?

**Comment by liarco** [comment]
Yes, `mintForAddress()` is meant to be used by the owner in order to send tokens to any address without paying for the token itself (gas fees are still applied).

**Comment by BlueGreninja** [comment]
> Yes, `mintForAddress()` is meant to be used by the owner in order to send tokens to any address without paying for the token itself (gas fees are still applied).

Quick question: Does the max mint amount apply for this function? Say we have set the Max Mint TX to 5 NFTs, will the 5 NFTs limit apply here ( Mint for address )?

**Comment by liarco** [comment]
@BlueGreninja all limits are applied to the owner as well, the only check that is bypassed is the "contract is paused" one. So the owner can mint even if the sale is closed, but he cannot overmint.

**Comment by gitrevo** [comment]
> @BlueGreninja all limits are applied to the owner as well, the only check that is bypassed is the "contract is paused" one. So the owner can mint even if the sale is closed, but he cannot overmint.

No wonder most contracts (Azuki, Tasty Bones etc.) implemented the "devMint" or similar which may serve the purpose of bypassing this limitation?

Shouldn't we implement this in the new ERC721A contract? Thanks Marco.

**Comment by liarco** [comment]
@gitrevo keeping the same limitations is intentional. We want to promote fair use of NFT collections and leaving unneeded huge power to the owner may lead to bad things. You can change the code if you wish, that would be a red flag if I were inspecting the code deciding whether to buy or not.

The owner should use those functions in order to mint just a few tokens for giveaways, if you need more then that it should be hard-coded and made clear from the beginning so users know how the supply is gonna be used.
