### ISSUE TITLE
Function has override specified but does not override anything

### ISSUE THREAD

**Issue by smartlapse** [hashlips-lab/nft-erc721-collection#61]
Hello, when I try to deploy the contract, I have this error with the new MAJ you have provide
![Capture d’écran 2022-03-04 à 18 40 10](https://user-images.githubusercontent.com/93977187/156814358-f518b3eb-0caa-4510-8974-102e015bbb90.png)
.

**Comment by liarco** [comment]
Hi @smartlapse,
Which version are you using? There is no `_startTokenId()` function in our `1.0.1` version.

If you are testing the code from #29 please make sure all dependencies are up-to-date with the lock files in the PR because they have been updated recently.

**Comment by smartlapse** [comment]
> 

When I copy the code from Github I have this error, but I have resolve this problem by download directly the zip ands change the "smart-contract" folder, I think that I forgot something, However, I changed everything (dependencies/Smart contract etc..).

**Comment by liarco** [comment]
@smartlapse stable releases can be found here: https://github.com/hashlips-lab/nft-erc721-collection/releases

The `main` branch (the one you see from the homepage of this repo) is the development branch, so you may find code that is not ready for production. I suggest downloading the full ZIP file from the latest release and start from scratch following the video linked in the README file.
