### ISSUE TITLE
Can I use the code , cause I have seen that it is migrated to erc721A!

### ISSUE THREAD

**Issue by Wajid4040** [hashlips-lab/nft-erc721-collection#63]
Hi, I was thinking to mint my 10000 nfts but I have seen the code has been updated to erc721A! 
can I use the code for minting now!

**Comment by liarco** [comment]
Sorry, I don't understand the question... also, please use [stable releases](https://github.com/hashlips-lab/nft-erc721-collection/releases) for production, the `main` branch contains code which is under development and should be used for testing only.
