### ISSUE TITLE
Couple quick questions on release 2.0 - hardware wallets and cost

### ISSUE THREAD

**Issue by joven1555** [hashlips-lab/nft-erc721-collection#65]
@liarco, Hashlips, & Team: I am BLOWN AWAY by 2.0 you are all truly amazing people and I'm pumped for Masterclass.  There are some MAJOR improvements with this release I'm seeing so far.  I had a couple question if it's alright, otherwise I will find the answers myself while I continue testing:

1. Since private keys are no longer needed and we can deploy using Truffle dashboard and Metamask, can we use a hardware wallet now from the start?  For instance providing the private keys with a Ledger was too dangerous in 1.0, but with Metamask we can simply confirm the transaction just like anything else.  I haven't tested it yet, but this will save time/money from having to transfer ownership to a HW wallet if it works through the CLI/Truffle using a Ledger without private keys being involved.

2. At 1:07:13 in the video (timestamp: https://youtu.be/Zhmj4PiJ-GA?t=4033) it appears you can now see the cost of contract deployment before deploying, is this right?  I won't be doing this on mainnet for a few weeks so just want to make sure I'm seeing this correctly.  If so, this is another HUGE improvement over 1.0 where you had no visibility to the cost of sending transactions to Etherscan.  This alone will make me want to use the CLI commands over manual updates like I was planning on doing.

Once again @liarco and Hashlips you guys really outdid yourself here!!  Thank you so much and not sure everyone else realizes how much incredible value you gave us here.  Using 721A is going to give everyone in the Hashlips community an extra advantage in the market as well.  <3

**Comment by liarco** [comment]
Thank you @joven1555, I really appreciate it.

1. You are right! Truffle Dashboard makes it possible to use MetaMask directly so HW wallets will be supported too
2. This is also correct, MetaMask is gonna show you every detail about the transaction that you are about to run (even estimated gas fees). You have to take CLI timeouts into account, but that's not hard to do 😉

I wish you the best of luck with your project!
