### ISSUE TITLE
Error  yarn rename-contract MyERC721

### ISSUE THREAD

**Issue by Drifter98** [hashlips-lab/nft-erc721-collection#66]
any help with this error pls :)
 yarn rename-contract MyERC721
yarn run v1.22.17
warning package.json: No license field
warning ..\..\..\package.json: No license field
$ hardhat rename-contract MyERC721
× Help us improve Hardhat with anonymous crash reports & basic usage data? (Y/n) · true

**Comment by liarco** [comment]
Hi @Drifter98,
That's actually not an error, it's Hardhat asking for permission to send anonymous usage data to them in order to improve the tool. You can either accept or refuse. 😉
