### ISSUE TITLE
Whitelist Mint Limit in Dapp

### ISSUE THREAD

**Issue by MrHetiBlox** [hashlips-lab/nft-erc721-collection#68]
@liarco 
I was testing the whitelist mint and encountered the problem that a person can only make 1 transaction during whitelist mint. For example, if a user mints 2 NFTs and the mint limit in the whitelist sale is 5. Then when that user wants to mint 2 more, the dapp won't let them do so.

![PROBLEM](https://user-images.githubusercontent.com/100795474/156919551-dad5de80-c0a7-4fe0-895f-1cc042cf83fe.png)

**Comment by juanantonionunez** [comment]
@MrHetiBlox https://github.com/hashlips-lab/nft-erc721-collection/issues/16#issuecomment-1046711923

**Comment by liarco** [comment]
Hi @MrHetiBlox,
it's not the DAPP, that's the contract and this works as intended: whitelist spots are "premium tickets for 1 single transaction at a discounted price", you can't use that "ticket" more than once, if you decide to mint less the the maximum, then you lose that chance.
This has be answered many times (e.g. https://github.com/hashlips-lab/nft-erc721-collection/issues/6#issuecomment-1046048038). If you wish to implement a different behavior you are free to customize it, but beware you might encounter unintended side-effects so you have to think about your changes carefully. 😉
