### ISSUE TITLE
getHexProof return empty array?

### ISSUE THREAD

**Issue by cptlchad** [hashlips-lab/nft-erc721-collection#72]
When calling this function, the result returns an empty string. Is that correct? Or what should be the expected return?
`this.getMerkleTree().getHexProof(keccak256(address));`

The merkle tree in the frontend looks the same as the one in the smart contract minus the "0x" part. And there is only one address in the json file for which I am trying to see the proof. I can perform the mint. Just curious if empty [] is really what the proof should be. Maybe you know more about it?

**Comment by liarco** [comment]
Hi @cptlchad a Merkle tree with a single address is an edge-case which might lead to unexpected results (I can confirm that having 1 address produces an empty proof). You should have at least 2 addresses in your WL.

Please let me know if you have issues even with 2 or more addresses.

**Comment by cptlchad** [comment]
Indeed it is. I tested it with more than 2 addresses and it works :)
