### ISSUE TITLE
background image repeats 

### ISSUE THREAD

**Issue by granthughes1999** [hashlips-lab/nft-erc721-collection#78]
i tried to add a background image directly into the index.html files. using the following structure 

<body>
<div class='bg-image' class="max-w-full h-full bg-no-repeat" style="background-image: url('/build/images/moon.jpg');">
<main>
      <div id="minting-dapp">
      </div>
    </main>
  </div>
</body>

and no matter what I try, I cannot get the background image to not repeat. in the x-axis across the page

**Comment by granthughes1999** [comment]
i just needed a larger photo....

**Comment by liarco** [comment]
Hi @granthughes1999,
you might also be interested in this example here: https://github.com/hashlips-lab/nft-erc721-collection/issues/46#issuecomment-1054274405

Have a nice day! 😉
