### ISSUE TITLE
It works flawless! Can I interact with the contract trough etherscan?

### ISSUE THREAD

**Issue by GoodGoldDev** [hashlips-lab/nft-erc721-collection#82]
Hi Marco,

Everything works flawless and perfect! I was just wondering if it is possible to interact with the contract through etherscan & via visual studio code?
I want to give some people NFT's that helped and I saw the mint-for-address option, or can I "yarn" that one too?

Kind regards,

Roemer.

**Comment by negaunee042** [comment]
Yes you should watch the video.  Not to be rude but that isn't an "issue".  Liarco is swamped I'm sure, and questions like this are meant for discord.  Every contract can be interacted thru etherscan if it's verified (for the owner, at least).  But watch the video.  All the answers and how to do it are there.  But the answer is yes to both, and to find out watch;
https://youtu.be/ynZzPNkS1nk

**Comment by GoodGoldDev** [comment]
Thanks a lot, I know the video but will watch it again. Also you are right to ask such questions on discord channel. I was just wondering if there were no sync problems and I could still use the visual studio code environment after updating through etherscan. Guess i missed it in the video ;) Cheers.
