### ISSUE TITLE
ProviderError: transaction underpriced

### ISSUE THREAD

**Issue by nftkk** [hashlips-lab/nft-erc721-collection#84]
Hi
i did download the version 3 to fix the "gas problem". Because i didnt find the way to work on the smart contract without private keys, i keep them inside the env.

The reason why i update is this error code:

yarn run v1.22.15
warning package.json: No license field
$ hardhat run scripts/2_whitelist_open.ts --network testnet
No need to generate any newer typings.
Updating the root hash to: 0xc42a82a68dbed0c3e93ac5fdd35c6ccd79e46b3c7b880327faefebedddf27b5e
**ProviderError: transaction underpriced**
    at HttpProvider.request (XXXXXXXXX\hashlips\nft-erc721-collection\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:74:19)
    at LocalAccountsProvider.request (XXXXXXXXX\hashlips\nft-erc721-collection\smart-contract\node_modules\hardhat\src\internal\core\providers\accounts.ts:182:36)   
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async EthersProviderWrapper.send (XXXXXXXXX\hashlips\nft-erc721-collection\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

i had the same issue when i was generating the smart contract. after several trys it works. but now i try to open the whitelist. i get the same issue again and again.

i thought that if i run the latest update that meta mask will open - so i can change the gas configurations. i hope you can help me. sorry for my bad english guys i hope you can understand me.

thanks

kayhan

**Comment by liarco** [comment]
Hi @nftkk, are you using Infura as provider? Are you working on Rinkeby?
This is really strange because the required gas is calculated by your provider and I never had such an issue using Infura on Rinkeby...

You can follow the [instructions by Daniel](https://youtu.be/Zhmj4PiJ-GA?t=3184) in order to use Truffle Dashboard and use MetaMask instead.

**Comment by nftkk** [comment]
Hi @liarco 
It was on the polygon testnet. i did try it on the main net. everything works perfect! in my case i was fine with it.

**Comment by liarco** [comment]
Hi @nftkk, thank you for the feedback. I must warn you that the current version doesn't officially support Polygon. You can customize it to do so (we are doing the same in #57), but until that will be properly tested you might encounter issues with your collection.

I hope the official support for Polygon will be released soon. 😉
