### ISSUE TITLE
please help - truffle install issue

### ISSUE THREAD

**Issue by Smartsdontgotit** [hashlips-lab/nft-erc721-collection#86]
This is what i get right after installing truffle and trying to open the dapp . please help thanks . 

truffle : File C:\Users\lootd\AppData\Roaming\npm\truffle.ps1 cannot be loaded because running 
scripts is disabled on this system. For more information, see about_Execution_Policies at       
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ truffle -v
+ ~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Users\lootd\OneDrive\Documents\new hash lab\nft-erc721-collection-2.0.0>

**Comment by negaunee042** [comment]
You have to go into powershell (run as admin)  and change the execution policy.  I got stuck on this for hours myself.  I unrestict for running my codes, then change back to unrestricted if i have no plans to run scripts for few days.  Be sure to run powershell as admin, not command prompt.  To unrestrict, run;

Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted

To change back, run;

Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Restricted

You must verify after each time by pressing Y for yest to confirm

**Comment by liarco** [comment]
Thank you @negaunee042, that's correct.

I suggest always checking the given errors carefully, because the following message seems quite self-explanatory:
```
truffle : File C:\Users\lootd\AppData\Roaming\npm\truffle.ps1 cannot be loaded because running
scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
```

It also contains a link to an article explaining the topic and what to do...

**Comment by Smartsdontgotit** [comment]
Will try this now - thank you so much for being so fast to answer. You guys are amazing people and one day there will be a group that sits in circles and sings folk songs about you. hehe . 

Thanks again will update shortly ;)
