### ISSUE TITLE
unable to verify contract

### ISSUE THREAD

**Issue by granthughes1999** [hashlips-lab/nft-erc721-collection#87]
for verification on the block explorer. Waiting for verification result...

I am met with this error message upon the verify contract step. it worked for me several times, now it throws these errors. even after restarting with a new zip file. 

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

**Comment by liarco** [comment]
You didn't use the search function... and you didn't even notice that there is a pinned issue on top of the "Issues" page about this exact topic... please respect our time.
