### ISSUE TITLE
URGENT Help - Can not Verify on MainNet 

### ISSUE THREAD

**Issue by ClubPEC** [hashlips-lab/nft-erc721-collection#88]
Hi Marco 

I am too having same error. Just deployed om main net paid real ETH but getting below error. I have used my API key in env file.

Error in plugin @nomiclabs/hardhat-etherscan: Please provide an Etherscan API token via hardhat config. For example:

{
  ...
  etherscan: {
    apiKey: {
      mainnet: 'your API key'
    }
  }
}

See https://etherscan.io/apis

For more info run Hardhat with --show-stack-traces       
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liarco** [comment]
Hi @ClubPEC,
what do you mean by "same error", same as what?

The API key is missing in your `.env` file. Did you update to `2.0.0`?

**Comment by ClubPEC** [comment]
> Hi @ClubPEC, what do you mean by "same error", same as what?
> 
> The API key is missing in your `.env` file. Did you update to `2.0.0`?

Hey Marco, 

Thank you for your reply however I solved the issue.

Some how Hardhat.config.ts wasn't reading - mainnet: process.env.BLOCK_EXPLORER_API_KEY,
So I simply Changed it with 
mainnet: "Your_Actual_API_Key", & delete mainnet: process.env.BLOCK_EXPLORER_API_KEY,

Now My contract is live and verified on Eth Mainnet

Thank you very much for all your guidance and help.

Please Support Penguin Exchange Club NFT project. @Club_pec

Thanks

**Comment by liarco** [comment]
Ok, you were probably missing the `BLOCK_EXPLORER_API_KEY` env variable in your `.env`, maybe you were using the old variable name from version `1.0.1`, which as changed in `2.0.0`.
