### ISSUE TITLE
Need some help please - cannot verify contract error 

### ISSUE THREAD

**Issue by Smartsdontgotit** [hashlips-lab/nft-erc721-collection#89]
I have deployed the contact to polygon , now when trying to verify this is the error. I cannot find the fix. Please help 

yarn verify 0x20f8cf77911a29641a80027a98466ea0743d110e --network truffle
yarn run v1.22.15
warning package.json: No license field
$ hardhat verify --constructor-args config/ContractArguments.ts 0x20f8cf77911a29641a80027a98466ea0743d110e --network truffle
× Help us improve Hardhat with anonymous crash reports & basic usage data? (Y/n) · true
Error in plugin @nomiclabs/hardhat-etherscan: Please provide an Etherscan API token via hardhat config. For example:

{
  ...
  etherscan: {
    apiKey: {
      polygon: 'your API key'
    }
  }
}
See https://etherscan.io/apis

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\lootd\OneDrive\Documents\new hash lab\nft-erc721-collection-2.0.0\smart-contract> yarn verify 0x20f8cf77911a29641a80027a98466ea0743d110e --network truffle
yarn run v1.22.15
warning package.json: No license field
$ hardhat verify --constructor-args config/ContractArguments.ts 0x20f8cf77911a29641a80027a98466ea0743d110e --network truffle
× Help us improve Hardhat with anonymous crash reports & basic usage data? (Y/n) · true
Error in plugin @nomiclabs/hardhat-etherscan: Please provide an Etherscan API token via hardhat config. For example:

{
  ...
  etherscan: {
    apiKey: {
      polygon: 'your API key'
    }
  }

See https://etherscan.io/apis

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\lootd\OneDrive\Documents\new hash lab\nft-erc721-collection-2.0.0\smart-contract>
PS C:\Users\lootd\OneDrive\Documents\new hash lab\nft-erc721-collection-2.0.0\smart-contract>

**Comment by Smartsdontgotit** [comment]
I have placed the api from polygon in the suggested place daniel states in the video and still getting this error

**Comment by h0rizons** [comment]
@liarco seems to be throwing the same error for a lot of people in Discord as well as myself again. It's the same one from the other day. Might be another hardhat / rinkeby / etherscan issue?

**Comment by h0rizons** [comment]
Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.

(Using 2.0 w/ Truffle)

**Comment by liarco** [comment]
@h0rizons Polygon support is not ready yet (see #57), you can test the PR branch if you wish but I can't support you with deploying an unstable version to production.
