### ISSUE TITLE
Smart Contract Yarn Error- Couldn't find the binary git

### ISSUE THREAD

**Issue by cesmith85** [hashlips-lab/nft-erc721-collection#90]
I'm getting an error when installing yarn dependencies for the smart contract. I tried installing git for windows; however, I'm still getting the same error message. 

<img width="493" alt="yarn-smart-contract-error" src="https://user-images.githubusercontent.com/77180053/157152042-f57a5d7b-9e98-4e28-832a-b594f5e8c715.png">

**Comment by yahyamtest** [comment]
Hi Cesmith85,

I have the same issue did you solve it?

Thanks.

**Comment by liarco** [comment]
@yahyamtest thank you very much for using the search instead of opening a new issue. 🙏

This is actually a duplicate of #5, I hope this helps.

**Comment by Patrizi5** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/97971328/157977498-3f7d829c-516f-4d70-9cae-d78d8df93e6e.png)
i need help with this
