### ISSUE TITLE
Allocate NFT Amount Per Sale

### ISSUE THREAD

**Issue by h0rizons** [hashlips-lab/nft-erc721-collection#91]
Is there any way we can allocate a certain amount of the total supply for each section of the sale?

The whitelist portion doesn't need it because the addresses get pulled from the .json.

For example, if you wanted to have the first 1,000 mints be free and wanted to use the presale function - is there a way to limit it to a certain #?

**Comment by GoodGoldDev** [comment]
There is a hashlip video regarding that: https://www.youtube.com/watch?v=B1XNN3rSoe4&t=149s
but that was in remix (although nice concept).

I think the quick fix solution could be (only if the NFTs will not me sold super quick) that you pauze the contract when the first 1000 mints are done. After that you update the price.

**Comment by liarco** [comment]
Hi @GoodGoldDev, this can be done and it shouldn't be too complicated, but unfortunately I don't have time to provide you with a custom example. You should change the code yourself or [hire a dev on the Discord server.](https://discord.gg/qh6MWhMJDN).
