### ISSUE TITLE
'replacement fee too low' - close and re-open the white-list

### ISSUE THREAD

**Issue by GoodGoldDev** [hashlips-lab/nft-erc721-collection#92]
Hi there, sometimes I have some difficulties to re-open the whitelist. (I do that to update the white-list like in the video).
There is an error now saying: 'replacement fee too low'

Is the whitelist getting too long?
Or is there a hash sync problem (opened the whitelist while it was open for example)?

Kind regards,

Roemer.

**Comment by liarco** [comment]
Hi @GoodGoldDev, I never had this issue before and I did some tests but I can't reproduce it.

Please provide the following information:
1. which web3 provider are you using? (e.g. Infura)
2. which network are you working on? (e.g. Rinkeby)
3. how many addresses are there in the whitelist?

I also found this issue that might be related, please take a look at it: https://github.com/ethers-io/ethers.js/issues/444

Anyway this kind of errors should not be related to our code, these are simply common issues with the provider estimating low gas fees or stuff like that.

**Comment by GoodGoldDev** [comment]
Hi Marco,

Now it is working again, it could be a flaw in the network? It started 12 hours ago. On the main network. Thanks anyway had to do something simple, sorry to bother with it.  Ill close it.

**Comment by liarco** [comment]
@GoodGoldDev don't worry, that's fine, those kind of errors might be scary at the beginning. With time you are gonna learn how to deal with them.
