### ISSUE TITLE
Deploy on Mainnet

### ISSUE THREAD

**Issue by ArabianAce** [hashlips-lab/nft-erc721-collection#95]
Hi, Liarco,
I am sorry I am taking your time again. Can you clear my confusion?

Did all steps of Rinkeby and everything was fine. Now when i have to deploy the smart contract on mainnet, do i need to repeat all the following steps? 

1) Install Truffle
2) Yarn install
3) Truffle dashboard and connect metamask using rinkeby
4) Smart contract configs
5) Contract deploy --network truffle (Where truffle is connected with Rinkeby network)
6) Contract verify
7) Contract address replaced in smart contract configs
8) Dapp things

Should I restart from Step 5 but with Mainnet? (command should be --network mainnet or --network truffle with truffle connected with my metamask mainnet network)??
The mainnet contract address will be different from rinkeby test net? (Will it be replaced in smart contract configs once again?
Should I add whitelists before deploying on the mainnet?

Thanks in Advance.

**Comment by liarco** [comment]
Hi @ArabianAce,
1. you can restart from `5`, just connecting MetaMask to mainnet (for Truffle Dashboard) or using `--network mainnet` depending on which method you do prefer
2. the contract address will be different and you will have to rebuild your DAPP after you update the contract address in the config
3. the `whitelist.json` file should be updated right before opening the whitelist sale (e.g. `yarn whitelist-open --network truffle`). If you change it later, you will have to open the whitelist sale again so the command will have the chance to update the Merkle root hash

Let me know if you need anything else. 😉

**Comment by ArabianAce** [comment]
Got it . Great
Same ethereum API will work out or a new one i shall create?

**Comment by liarco** [comment]
Infura is required only when using `--network testnet` or `--network mainnet`, you don't need that when using `--network truffle`... but in case you need it, just make sure you are setting the correct endpoints for `testnet` and `mainnet`, then you can use the same Infura project for both.

**Comment by ArabianAce** [comment]
So, Truffle all the way.

Thank you for so much of your help.

**Comment by VeriumNFT** [comment]
> Hi @ArabianAce,
> 
> 1. you can restart from `5`, just connecting MetaMask to mainnet (for Truffle Dashboard) or using `--network mainnet` depending on which method you do prefer
> 2. the contract address will be different and you will have to rebuild your DAPP after you update the contract address in the config
> 3. the `whitelist.json` file should be updated right before opening the whitelist sale (e.g. `yarn whitelist-open --network truffle`). If you change it later, you will have to open the whitelist sale again so the command will have the chance to update the Merkle root hash
> 
> Let me know if you need anything else. 😉

Hey @liarco 

So I'm running into this issue. I believe I message about it before and you said to make sure that the contract address has been changed in the configuration. I made sure that I updated the line contractAddress: "", with the main net address. I double, triple, quadruple checked I correctly copied the address. I ran yarn build and then re-uploaded the files to my public domain. It says it cannot load the contract data and to make sure I'm connected to the right network. I am currently staring at MetaMask extension saying 'Ethereum Network'. I removed the build files created from my public domain. Ran build again and uploaded them a third time and it still isn't connecting. I then navigated to edit the main.js file inside my root folder directly. I searched for the term contractaddress and found the configuration settings that include the marketplace identifier and token name. The address shown is the one I changed it to and matches the mainnet contract address. Is there any other reason why it is still not connecting? I tried clearing my cache, closing out all metamask sessions and restarted my browser but nothing works. I appreciate any help and sincerely apologize for asking something you hear 100 times a day.

**Comment by VeriumNFT** [comment]
Update: 

> > Hi @ArabianAce,
> > 
> > 1. you can restart from `5`, just connecting MetaMask to mainnet (for Truffle Dashboard) or using `--network mainnet` depending on which method you do prefer
> > 2. the contract address will be different and you will have to rebuild your DAPP after you update the contract address in the config
> > 3. the `whitelist.json` file should be updated right before opening the whitelist sale (e.g. `yarn whitelist-open --network truffle`). If you change it later, you will have to open the whitelist sale again so the command will have the chance to update the Merkle root hash
> > 
> > Let me know if you need anything else. 😉
> 
> Hey @liarco
> 
> So I'm running into this issue. I believe I message about it before and you said to make sure that the contract address has been changed in the configuration. I made sure that I updated the line contractAddress: "", with the main net address. I double, triple, quadruple checked I correctly copied the address. I ran yarn build and then re-uploaded the files to my public domain. It says it cannot load the contract data and to make sure I'm connected to the right network. I am currently staring at MetaMask extension saying 'Ethereum Network'. I removed the build files created from my public domain. Ran build again and uploaded them a third time and it still isn't connecting. I then navigated to edit the main.js file inside my root folder directly. I searched for the term contractaddress and found the configuration settings that include the marketplace identifier and token name. The address shown is the one I changed it to and matches the mainnet contract address. Is there any other reason why it is still not connecting? I tried clearing my cache, closing out all metamask sessions and restarted my browser but nothing works. I appreciate any help and sincerely apologize for asking something you hear 100 times a day.

Update: So I deleted the build folder contents from my root directory and it still stores the files somehow and I can still see the site. I checked the inspected the web page using Chrome and navigated to the /build/main.js file location only to see that the test contract address is still there. Some how it's cached the build files and won't let me overwrite them. Might be my web host I'll reach out to them as well for more info.

**Comment by VeriumNFT** [comment]
Solution: 

> Update:
> 
> > > Hi @ArabianAce,
> > > 
> > > 1. you can restart from `5`, just connecting MetaMask to mainnet (for Truffle Dashboard) or using `--network mainnet` depending on which method you do prefer
> > > 2. the contract address will be different and you will have to rebuild your DAPP after you update the contract address in the config
> > > 3. the `whitelist.json` file should be updated right before opening the whitelist sale (e.g. `yarn whitelist-open --network truffle`). If you change it later, you will have to open the whitelist sale again so the command will have the chance to update the Merkle root hash
> > > 
> > > Let me know if you need anything else. 😉
> > 
> > 
> > Hey @liarco
> > So I'm running into this issue. I believe I message about it before and you said to make sure that the contract address has been changed in the configuration. I made sure that I updated the line contractAddress: "", with the main net address. I double, triple, quadruple checked I correctly copied the address. I ran yarn build and then re-uploaded the files to my public domain. It says it cannot load the contract data and to make sure I'm connected to the right network. I am currently staring at MetaMask extension saying 'Ethereum Network'. I removed the build files created from my public domain. Ran build again and uploaded them a third time and it still isn't connecting. I then navigated to edit the main.js file inside my root folder directly. I searched for the term contractaddress and found the configuration settings that include the marketplace identifier and token name. The address shown is the one I changed it to and matches the mainnet contract address. Is there any other reason why it is still not connecting? I tried clearing my cache, closing out all metamask sessions and restarted my browser but nothing works. I appreciate any help and sincerely apologize for asking something you hear 100 times a day.
> 
> Update: So I deleted the build folder contents from my root directory and it still stores the files somehow and I can still see the site. I checked the inspected the web page using Chrome and navigated to the /build/main.js file location only to see that the test contract address is still there. Some how it's cached the build files and won't let me overwrite them. Might be my web host I'll reach out to them as well for more info.

**Solution:** Hello everyone, after giving my brain some rest I realized by changing the directory folder name inside entrypoints.json and manifest.json from something like /build/ to /build2/ then placing the updated build files into the new build2 folder in my root folder. To avoid the images from breaking keep them stored in the same directory /build/images. I hope this helps.

**Comment by liarco** [comment]
Hi @VeriumETH, sorry for the delay but I'm really happy you found a solution. Also thank you very much for sharing details about your troubleshooting steps, this content might be very useful to other people.
