### ISSUE TITLE
unable to verify

### ISSUE THREAD

**Issue by hamhocks** [hashlips-lab/nft-erc721-collection#99]
Hi 
thanks for the great program. When I go to verify I get an error:
Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.Reason: Fail - Unable to verify

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
I've been trying for days to figure out any suggestions.
thanks

**Comment by liarco** [comment]
Hi @hamhocks please use the search feature to make sure your question has not already been asked. There is issue #83 pinned in the issues homepage about this topic. 😉

Thank you
